In [1]:
import tensorflow as tf

In [13]:
data = tf.random.uniform((2,3),3,100,dtype=tf.float32)

In [23]:
data

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[28.943457, 55.324215, 50.168613],
       [74.50713 , 11.473842, 25.035131]], dtype=float32)>

In [24]:
# rsqrt
rsqrt = tf.math.rsqrt(data)

In [25]:
rsqrt

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.18587662, 0.1344443 , 0.14118351],
       [0.11585134, 0.29521987, 0.19985962]], dtype=float32)>

In [26]:
# const input 1
const_1 = tf.constant(1, shape = (2,3),dtype = tf.float32)

In [27]:
const_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [31]:
add_1 = tf.math.add(rsqrt,const_1)

In [32]:
add_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.1858766, 1.1344442, 1.1411835],
       [1.1158514, 1.2952199, 1.1998596]], dtype=float32)>

In [33]:
const_2 = tf.constant(3, shape = (2,3),dtype = tf.float32)

In [34]:
add_2 = tf.math.add(add_1, const_2)

In [35]:
add_2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[4.185877 , 4.134444 , 4.1411834],
       [4.1158514, 4.29522  , 4.1998596]], dtype=float32)>