In [1]:
import torch
import torch.nn as nn
torch.set_printoptions(precision=9,sci_mode=False)

In [2]:
conv2d_padding_1 = nn.Conv2d(3,6,3,1,1)

In [3]:
conv2d_padding_0 = nn.Conv2d(3,6,3,1,0)

In [4]:
in_tensor = torch.randn((2,3,4,4),dtype=torch.float32)

In [5]:
#输入的nhwc格式
in_tensor.permute(0,2,3,1).flatten()

tensor([ 0.076667599,  0.711138487, -1.008811116, -2.163321018,  1.400167465,
         2.252756834,  1.579253793, -0.323564202, -0.367994159,  0.181753278,
        -0.224710897, -2.290348291, -0.587909222,  0.161353901, -0.679489076,
        -1.104076743,  0.397905350, -0.788385510, -0.614677846,  1.286626101,
        -0.507996380,  1.359352946,  1.893435240,  1.429053187, -0.348665655,
        -0.699571013,  0.331353843,  1.292119503,  1.096986294,  0.192839980,
        -0.496053129, -0.454451442,  0.071561962,  0.222182140,  0.066973791,
         0.382464945, -0.534260571,  2.211821556,  0.006850300,  0.091810793,
        -0.086833216, -0.822240531, -0.060139883, -0.214218095, -0.425117165,
        -0.922640979,  0.621625185,  0.420081288, -0.411268413, -0.084119007,
         0.670962811, -0.644684374,  1.771083951,  0.649320006,  1.715489030,
        -0.356252283,  0.866390824,  0.505115390,  1.561913729, -1.585212231,
         0.480017811,  1.347705722,  0.743289053, -0.078392923, 

In [6]:
padding_0_result = conv2d_padding_0(in_tensor)

In [7]:
padding_1_result = conv2d_padding_1(in_tensor)

In [8]:
padding_0_result.shape

torch.Size([2, 6, 2, 2])

In [9]:
padding_1_result.shape

torch.Size([2, 6, 4, 4])

In [10]:
in_tensor_another = torch.randn((2,3,3,3),dtype=torch.float32)

* 保存权重值

In [11]:
padding_1_weight = conv2d_padding_1.weight.detach()

In [12]:
padding_1_weight = padding_1_weight.permute(0,2,3,1)

In [13]:
padding_1_bias = conv2d_padding_1.bias.detach()

In [14]:
padding_1_bin = torch.cat([padding_1_weight.flatten(),padding_1_bias],0)

In [15]:
padding_1_bin.flatten()

tensor([ 0.032229379, -0.154418290,  0.073423371,  0.162324056, -0.135344416,
         0.146334067, -0.094873726, -0.108123742,  0.164595798,  0.192123875,
         0.139730856,  0.187376037,  0.078908190,  0.144893661, -0.038976669,
         0.180282399,  0.041281104, -0.166389555, -0.127706677,  0.066077843,
        -0.126256973, -0.086403579, -0.148346543, -0.056353867, -0.103490934,
         0.014741629,  0.017700061, -0.136965647, -0.114728123,  0.063593104,
         0.141314015, -0.044161662, -0.130596042, -0.096805178,  0.105191186,
         0.119307503,  0.126001969, -0.072871335, -0.028838173,  0.012457415,
        -0.142589897, -0.027796030,  0.115895972, -0.062293470,  0.134820119,
         0.117584571, -0.000617325, -0.160156637, -0.132056177, -0.039220586,
         0.186518148,  0.019377366, -0.171850175, -0.107616447, -0.136765838,
         0.153502956,  0.121273443,  0.048494846,  0.025119290,  0.109424874,
         0.141779587,  0.069584057,  0.155044332,  0.063922837, 

In [16]:
padding_1_bin.numpy().tofile("./2dconv_6_3_3_3.bin")

In [17]:
padding_1_result.permute(0,2,3,1).flatten()

tensor([-0.248866037, -0.172505558, -0.321258873, -0.841765285,  0.509426534,
         0.619648635,  0.666382194, -0.309837431,  0.586357772, -0.249248579,
        -0.708610117, -0.210742101,  0.907460093, -1.163459778,  0.539601564,
         1.064230800, -0.616100907,  0.286206782,  0.147525713,  0.346691549,
        -0.215106890, -0.253742367,  0.973052323,  0.351108193,  0.284785956,
         0.411709219,  0.455479026,  0.235334024,  0.089625604,  0.159975678,
        -0.901910245, -1.599553108, -0.167759016, -0.857110739,  0.352267563,
         1.473780394, -0.192660734,  0.323008955,  0.874087632, -1.110815167,
        -0.851645231,  0.084775008,  0.203056172, -0.352852821, -0.134220988,
        -0.107010953, -1.036238551, -0.932074666, -0.349622548,  0.331574947,
        -0.541813850, -0.419313937,  0.145986915,  0.731243730, -0.177181184,
        -0.236804098, -0.258403897, -0.479694426,  0.428942621, -0.315372139,
         0.105234109,  0.327413142,  0.868290484, -0.231857806, 

In [18]:
padding_1_result.numel()

192

In [21]:
padding_1_result.shape

torch.Size([2, 6, 4, 4])

In [19]:
conv2d_padding_1

Conv2d(3, 6, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))

In [20]:
padding_1_bin.numel()*4

672