In [1]:
import tensorflow as tf

In [2]:
indices = [0,1,2]

In [3]:
depth = 3

In [4]:
tf.one_hot(indices,depth)

<tf.Tensor: id=4, shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [5]:
indices = [0,1,6,2]

In [6]:
tf.one_hot(indices,depth,axis=0)

<tf.Tensor: id=9, shape=(3, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [7]:
batch_indices = [[0,2],[1,-1]]

In [8]:
depth =3

In [9]:
tf.one_hot(batch_indices,depth,axis=0)

<tf.Tensor: id=14, shape=(3, 2, 2), dtype=float32, numpy=
array([[[1., 0.],
        [0., 0.]],

       [[0., 0.],
        [1., 0.]],

       [[0., 1.],
        [0., 0.]]], dtype=float32)>

In [10]:
test = [[[1,2],[0,1]] , [[2,2],[3,3]]]

In [11]:
tf.one_hot(test,depth,axis=1)

<tf.Tensor: id=19, shape=(2, 3, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [1., 0.]],

        [[1., 0.],
         [0., 1.]],

        [[0., 1.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[1., 1.],
         [0., 0.]]]], dtype=float32)>

In [12]:
import numpy as np