In [1]:
import tensorflow.keras.preprocessing as prep

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
import numpy as np
import pandas as pd

In [4]:
import random

In [1]:
import tensorflow as tf

In [2]:
import torch

In [7]:
import onnx

In [9]:
from onnx_tf.backend import prepaare

/opt/anaconda3/envs/d2l/lib/python3.7/site-packages/tensorflow_addons/utils/ensure_tf_install.py:67: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.3.0 and strictly below 2.5.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.0.0 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version. 
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  UserWarning,


ImportError: cannot import name 'keras_tensor' from 'tensorflow.python.keras.engine' (/opt/anaconda3/envs/d2l/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/__init__.py)

In [ ]:
part_2_path = "/Users/bob/docs/ByteDance/espresso/part_1.onnx"

In [ ]:
part_2_model = onnx.load(part_2_path)

In [ ]:
part_2_model

In [1]:
import time

In [3]:
int(time.time() * 1000)

1628575796812

In [8]:
a = tf.constant([
    [
        [
            [1],[1],[1]
        ],
        [
            [2],[2],[2]
        ]
    ]
    ,
        [
        [
            [3],[3],[3]
        ],
        [
            [4],[4],[4]
        ]
    ]
])

In [12]:
a

<tf.Tensor: shape=(2, 2, 3, 1), dtype=int32, numpy=
array([[[[1],
         [1],
         [1]],

        [[2],
         [2],
         [2]]],


       [[[3],
         [3],
         [3]],

        [[4],
         [4],
         [4]]]], dtype=int32)>

In [13]:
gamma = tf.constant([
    [
        [
            [2],[3],[2]
        ]
    ]
])

In [14]:
gamma

<tf.Tensor: shape=(1, 1, 3, 1), dtype=int32, numpy=
array([[[[2],
         [3],
         [2]]]], dtype=int32)>

In [15]:
a*gamma

<tf.Tensor: shape=(2, 2, 3, 1), dtype=int32, numpy=
array([[[[ 2],
         [ 3],
         [ 2]],

        [[ 4],
         [ 6],
         [ 4]]],


       [[[ 6],
         [ 9],
         [ 6]],

        [[ 8],
         [12],
         [ 8]]]], dtype=int32)>

In [16]:
a

<tf.Tensor: shape=(2, 2, 3, 1), dtype=int32, numpy=
array([[[[1],
         [1],
         [1]],

        [[2],
         [2],
         [2]]],


       [[[3],
         [3],
         [3]],

        [[4],
         [4],
         [4]]]], dtype=int32)>

In [24]:
test = tf.random.uniform(shape=(2,2,3,2), minval=1, maxval=5, dtype=tf.int32)

In [26]:
tf.transpose(test, perm = [3,0,1,2])

<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
array([[[[4, 2, 4],
         [4, 2, 4]],

        [[1, 1, 2],
         [1, 3, 2]]],


       [[[3, 3, 2],
         [1, 4, 3]],

        [[4, 2, 3],
         [1, 4, 3]]]], dtype=int32)>

In [23]:
tf.reshape(test, shape=(1,2,2,3))

<tf.Tensor: shape=(1, 2, 2, 3), dtype=int32, numpy=
array([[[[2, 4, 1],
         [4, 3, 2]],

        [[3, 1, 1],
         [4, 2, 4]]]], dtype=int32)>

In [15]:
import numpy

In [16]:
data = [
    -0.915259957,
0.611176669,
-4.27415752,
-2.29328966,
-14.4080076,
0.396923482,
-0.807463586,
-1.21548533,
1.08540905,
0.0134548079,
-0.34603706,
0.282633245,
-0.718247294,
-0.529765964,
-0.396382093,
1.12900615,
-0.888921618,
0.152252108,
-1.59450328,
0.435953915,
-0.189245164,
-2.97230315,
0.835833072,
2.05819201,
-0.363298029,
0.263530284,
0.367984384,
2.48542523,
0.18496868,
-2.58495331,
-1.10956693,
-0.0470633954,
-7.10666895,
3.58766937,
-1.20936143,
-2.95472074,
-2.37228703,
0.535582006,
-0.791666805,
-0.966980159,
3.81039095,
1.16736233,
-0.172302499,
0.380082816,
-0.609364152,
-0.53191036,
-1.27164352,
-1.03939736,
-1.15881562,
-0.362319291,
-0.862555384,
0.962290644,
-0.873375713,
-11.7827539,
1.08341897,
1.93683553,
-25.6555519,
-7.73447895,
0.193249151,
3.98868608,
0.495604038,
3.25697088,
-1.3660481,
0.778017759,
-0.177881077,
1.17199707,
1.91775441,
-2.9150331,
-0.581937551,
-1.17758846,
-0.775810301,
-0.732436776,
1.09170914,
-0.246044099,
-3.22675896,
0.764951348,
-0.71387434,
-0.937960326,
-0.953298449,
-0.30390662,
-1.49382281,
-0.239211351,
-0.552626133,
-0.415805131,
-0.738390445,
13.0474396,
1.10336947,
1.28709352,
-1.00341868,
6.93061065,
0.192094028,
0.253703922,
0.055308301,
-0.278131545,
-1.57116413,
0.380545378,
-2.01941609,
0.0870193466,
-1.18693972,
-3.05277371,
13.0976419,
21.9392433,
-2.99633765,
-0.0274555217,
1.67631507,
-0.803175508,
-1.74668682,
0.697305918,
-1.38456523,
0.77429521,
-2.61394024,
13.0507145,
-0.359760284,
7.19971466,
1.14251471,
0.53356415,
0.225418523,
-14.9436607,
1.79381418,
2.06300783,
-0.252913922,
0.449480921,
-0.409070283,
-3.85661459,
0.877940416,
-4.2389555,
-1.31837785,
0.945552587,
14.2239161,
-10.5016699,
0.530112863,
-2.78076315,
9.56580162,
0.998134434,
7.53920936,
1.39592659,
-10.1667156,
-4.78861284,
0.463591665,
0.89286071,
-0.648308158,
0.970494031,
12.6412935,
-9.01614093,
-0.619920969,
-6.64220667,
1.44414175,
1.22875047,
-0.149289176,
-18.4423771,
-8.71438884,
1.75846386,
0.97143197,
7.16379833,
0.717568099,
-9.10100269,
0.459422201,
3.83135247,
5.01032639,
2.45652437,
-2.21893764,
0.174057931,
1.35654402,
-2.65468121,
-4.23505068,
-22.6787891,
1.36064577,
0.831576168,
1.80253136,
-0.530671477,
7.64629889,
0.028618725,
-1.70763218,
-0.319835275,
-2.98995972,
-3.15847635,
-0.654392719,
0.457244039,
-0.29946354,
-0.119668178,
-1.15742624,
7.5199213,
0.887380301,
1.59932041,
1.17170215,
-6.98499727,
-0.115877479,
0.399549514,
-0.219754472,
1.71459365,
0.28215459,
1.08361483,
-1.12965155,
0.18026042,
2.60229564,
-2.1561296,
7.54194736,
-1.14358497,
-0.937893927,
-0.398247927,
0.451163322,
-0.565263689,
-0.813935279,
0.225313067,
-0.839385151,
0.952487468,
-0.356312245,
-0.211776718,
-1.31979084,
-0.248198181,
2.04341507,
-0.75630635,
-0.222813964,
19.5297165,
0.849772632,
1.75866175,
1.13220596,
-0.601775467,
0.107098624,
1.05411303,
0.115286782,
-0.375014246,
-0.557319283,
-3.28868294,
1.20621097,
1.68256748,
1.11271572,
-2.26252055,
-0.285304129,
0.564513326,
-1.30720592,
1.06905723,
-0.533148646,
7.89167643,
-1.6186235,
0.225931734,
-0.664122701,
0.655531346,
-2.63413596,
-0.20867008,
-1.24916279,
0.0498736687,
0.44960019,
-0.399693638,
-0.992818772,
7.89789248,
1.2967608,
1.45309234,
23.7009716,
0.587704718,
1.39824581,
2.15966439,
-0.28969413,
-0.039310541,
-0.552492082,
-0.225315943,
-0.78494513,
0.86429286,
-0.418945879,
-2.25991988,
-8.15540027,
0.219293624,
-1.11092091,
0.305982918,
0.314763576,
-1.15800393,
0.0965895652,
0.00546424976,
-1.1854645,
-0.150175825,
-0.0893826932,
0.0774724707,
-1.41997349,
-0.206657812,
-1.62680376,
-0.813599228,
-1.57142115,
0.176346228,
0.833469629,
1.31116569,
0.122265577,
-0.114011422,
0.677672386,
0.295245677,
0.0457631722,
-1.17871511,
2.55578518,
0.369716495
]

In [17]:
tensor = tf.constant(data, dtype = tf.float32, shape = (3,3,32,1))

In [18]:
orig_weight = [-0.915259957,
0.611176669,
-4.27415752,
-2.29328966,
-14.4080076,
0.396923482,
-0.807463586,
-1.21548533,
1.08540905,
0.0134548079,
-0.34603706,
0.282633245,
-0.718247294,
-0.529765964,
-0.396382093,
1.12900615,
-0.888921618,
0.152252108,
-1.59450328,
0.435953915,
-0.189245164,
-2.97230315,
0.835833072,
2.05819201,
-0.363298029,
0.263530284,
0.367984384,
2.48542523,
0.18496868,
-2.58495331,
-1.10956693,
-0.0470633954,
-7.10666895,
3.58766937,
-1.20936143,
-2.95472074,
-2.37228703,
0.535582006,
-0.791666805,
-0.966980159,
3.81039095,
1.16736233,
-0.172302499,
0.380082816,
-0.609364152,
-0.53191036,
-1.27164352,
-1.03939736,
-1.15881562,
-0.362319291,
-0.862555384,
0.962290644,
-0.873375713,
-11.7827539,
1.08341897,
1.93683553,
-25.6555519,
-7.73447895,
0.193249151,
3.98868608,
0.495604038,
3.25697088,
-1.3660481,
0.778017759,
-0.177881077,
1.17199707,
1.91775441,
-2.9150331,
-0.581937551,
-1.17758846,
-0.775810301,
-0.732436776,
1.09170914,
-0.246044099,
-3.22675896,
0.764951348,
-0.71387434,
-0.937960326,
-0.953298449,
-0.30390662,
-1.49382281,
-0.239211351,
-0.552626133,
-0.415805131,
-0.738390445,
13.0474396,
1.10336947,
1.28709352,
-1.00341868,
6.93061065,
0.192094028,
0.253703922,
0.055308301,
-0.278131545,
-1.57116413,
0.380545378,
-2.01941609,
0.0870193466,
-1.18693972,
-3.05277371,
13.0976419,
21.9392433,
-2.99633765,
-0.0274555217,
1.67631507,
-0.803175508,
-1.74668682,
0.697305918,
-1.38456523,
0.77429521,
-2.61394024,
13.0507145,
-0.359760284,
7.19971466,
1.14251471,
0.53356415,
0.225418523,
-14.9436607,
1.79381418,
2.06300783,
-0.252913922,
0.449480921,
-0.409070283,
-3.85661459,
0.877940416,
-4.2389555,
-1.31837785,
0.945552587,
14.2239161,
-10.5016699,
0.530112863,
-2.78076315,
9.56580162,
0.998134434,
7.53920936,
1.39592659,
-10.1667156,
-4.78861284,
0.463591665,
0.89286071,
-0.648308158,
0.970494031,
12.6412935,
-9.01614093,
-0.619920969,
-6.64220667,
1.44414175,
1.22875047,
-0.149289176,
-18.4423771,
-8.71438884,
1.75846386,
0.97143197,
7.16379833,
0.717568099,
-9.10100269,
0.459422201,
3.83135247,
5.01032639,
2.45652437,
-2.21893764,
0.174057931,
1.35654402,
-2.65468121,
-4.23505068,
-22.6787891,
1.36064577,
0.831576168,
1.80253136,
-0.530671477,
7.64629889,
0.028618725,
-1.70763218,
-0.319835275,
-2.98995972,
-3.15847635,
-0.654392719,
0.457244039,
-0.29946354,
-0.119668178,
-1.15742624,
7.5199213,
0.887380301,
1.59932041,
1.17170215,
-6.98499727,
-0.115877479,
0.399549514,
-0.219754472,
1.71459365,
0.28215459,
1.08361483,
-1.12965155,
0.18026042,
2.60229564,
-2.1561296,
7.54194736,
-1.14358497,
-0.937893927,
-0.398247927,
0.451163322,
-0.565263689,
-0.813935279,
0.225313067,
-0.839385151,
0.952487468,
-0.356312245,
-0.211776718,
-1.31979084,
-0.248198181,
2.04341507,
-0.75630635,
-0.222813964,
19.5297165,
0.849772632,
1.75866175,
1.13220596,
-0.601775467,
0.107098624,
1.05411303,
0.115286782,
-0.375014246,
-0.557319283,
-3.28868294,
1.20621097,
1.68256748,
1.11271572,
-2.26252055,
-0.285304129,
0.564513326,
-1.30720592,
1.06905723,
-0.533148646,
7.89167643,
-1.6186235,
0.225931734,
-0.664122701,
0.655531346,
-2.63413596,
-0.20867008,
-1.24916279,
0.0498736687,
0.44960019,
-0.399693638,
-0.992818772,
7.89789248,
1.2967608,
1.45309234,
23.7009716,
0.587704718,
1.39824581,
2.15966439,
-0.28969413,
-0.039310541,
-0.552492082,
-0.225315943,
-0.78494513,
0.86429286,
-0.418945879,
-2.25991988,
-8.15540027,
0.219293624,
-1.11092091,
0.305982918,
0.314763576,
-1.15800393,
0.0965895652,
0.00546424976,
-1.1854645,
-0.150175825,
-0.0893826932,
0.0774724707,
-1.41997349,
-0.206657812,
-1.62680376,
-0.813599228,
-1.57142115,
0.176346228,
0.833469629,
1.31116569,
0.122265577,
-0.114011422,
0.677672386,
0.295245677,
0.0457631722,
-1.17871511,
2.55578518,
0.369716495]

In [19]:
weight_tensor = tf.constant(orig_weight, shape = (1,3,3,32), dtype = tf.float32)

In [20]:
scale = tf.constant([0.79812473,
1.02470672,
0.234702155,
0.584702015,
1.47273922,
1.65369105,
0.207335263,
0.253795445,
1.74145031,
0.851999104,
0.285381347,
0.0487552546,
0.619520783,
0.658530533,
0.462138057,
0.997453808,
0.514498651,
0.881484925,
0.226436034,
0.794034004,
0.176940665,
1.25603747,
1.08425307,
0.481042415,
1.55542338,
1.30222631,
-0.0969873368,
0.840993523,
0.0373481698,
1.28414547,
0.509954929,
0.82484883],shape = (1,1,1,32), dtype = tf.float32)

In [21]:
offset = tf.constant([1.74432492,
3.22856832,
-0.164343342,
-0.151181191,
3.41901779,
2.9530704,
0.509777009,
-0.22501117,
3.29713655,
1.05740237,
0.15488711,
-0.36347121,
-0.436501116,
-1.04766357,
2.89067554,
2.63541865,
-0.519024551,
1.43494928,
2.56361675,
-1.3595705,
-0.166126043,
2.40421009,
-0.0780990198,
-1.22872186,
3.07737827,
2.9610846,
-0.147120178,
2.70570183,
-0.359455556,
2.39848304,
-0.579904437,
-0.323385626],shape = (1,1,1,32), dtype = tf.float32)

In [22]:
mean = tf.constant([2.83318233,
-6.53696203,
0.0420894213,
-3.90999813E-36,
1.27528048,
-0.762632012,
0.0138975857,
3.91655755E-36,
-1.63337111,
2.17463207,
0.0931125953,
3.91609192E-36,
-3.91780558E-36,
3.90671214E-36,
3.92310977,
0.766388356,
-0.10357853,
0.174043208,
0.00519207632,
3.91023956E-36,
-13.6242762,
-1.58756614,
-0.244740307,
3.34658194,
-0.238025799,
-0.150351256,
0.699682236,
-6.87351561,
0.149567708,
0.404550731,
0.278983235,
11.8062963,
], dtype = tf.float32, shape = (1,1,1,32))

In [23]:
variance = tf.constant([  52.9916306,
  98.6942443,
  1.07424688,
  3.90845594E-36,
  57.062622,
  296.507599,
  0.411148727,
  3.91267929E-36,
  110.319336,
  26.4148273,
  5.2001071,
  3.91252109E-36,
  3.91761222E-36,
  3.91278261E-36,
  21.3122597,
  70.8626938,
  0.0140138669,
  35.9642715,
  0.0347588137,
  3.91159879E-36,
  13.3438597,
  141.240005,
  10.2351866,
  26.5206547,
  415.62619,
  24.5138931,
  0.232058972,
  87.2247086,
  0.00013200994,
  3.68522573,
  3.7254498,
  4.24222136,
], dtype = tf.float32, shape = (1,1,1,32))

In [24]:
alpha = scale / tf.math.sqrt(variance + 0.0010000000474974513)

In [30]:
bias = offset - scale * mean / tf.math.sqrt(variance + 0.0010000000474974513)

In [31]:
bias

<tf.Tensor: shape=(1, 1, 1, 32), dtype=float32, numpy=
array([[[[ 1.4336991e+00,  3.9028285e+00, -1.7386989e-01,
          -1.5118119e-01,  3.1703887e+00,  3.0263109e+00,
           5.0528866e-01, -2.2501117e-01,  3.5679488e+00,
           6.9691271e-01,  1.4323549e-01, -3.6347121e-01,
          -4.3650112e-01, -1.0476636e+00,  2.4979608e+00,
           2.5446095e+00, -8.4106207e-02,  1.4093676e+00,
           2.5573995e+00, -1.3595705e+00,  4.9378291e-01,
           2.5719955e+00,  4.8415661e-03, -1.5413187e+00,
           3.0955384e+00,  3.0006285e+00, -6.5532923e-03,
           3.3246429e+00, -5.2548385e-01,  2.1279027e+00,
          -6.5360355e-01, -5.0509801e+00]]]], dtype=float32)>

In [25]:
alpha

<tf.Tensor: shape=(1, 1, 1, 32), dtype=float32, numpy=
array([[[[ 0.10963849,  0.10314579,  0.22634086, 18.4899    ,
           0.1949603 ,  0.09603638,  0.32295808,  8.025716  ,
           0.16579953,  0.16577041,  0.12513469,  1.5417764 ,
          19.590965  , 20.824562  ,  0.10010293,  0.11848979,
           4.1989236 ,  0.14698507,  1.1974407 , 25.109558  ,
           0.04843626,  0.10568715,  0.3388922 ,  0.09340779,
           0.07629511,  0.26300952, -0.20090102,  0.09004723,
           1.1100543 ,  0.66884154,  0.2641704 ,  0.4004299 ]]]],
      dtype=float32)>

In [26]:
weight_tensor * alpha

<tf.Tensor: shape=(1, 3, 3, 32), dtype=float32, numpy=
array([[[[-1.00347720e-01,  6.30403012e-02, -9.67416465e-01,
          -4.24026985e+01, -2.80898952e+00,  3.81190963e-02,
          -2.60776877e-01, -9.75514030e+00,  1.79960310e-01,
           2.23040907e-03, -4.33012396e-02,  4.35757279e-01,
          -1.40711575e+01, -1.10321445e+01, -3.96790095e-02,
           1.33775696e-01, -3.73251390e+00,  2.23787874e-02,
          -1.90932322e+00,  1.09466105e+01, -9.16632731e-03,
          -3.14134240e-01,  2.83257306e-01,  1.92251161e-01,
          -2.77178623e-02,  6.93109706e-02, -7.39284381e-02,
           2.23805666e-01,  2.05325276e-01, -1.72892416e+00,
          -2.93114752e-01, -1.88455917e-02],
         [-7.79164433e-01,  3.70052963e-01, -2.73727894e-01,
          -5.46324921e+01, -4.62501794e-01,  5.14353588e-02,
          -2.55675197e-01, -7.76070786e+00,  6.31761014e-01,
           1.93514138e-01, -2.15610210e-02,  5.86002707e-01,
          -1.19380322e+01, -1.10768003e+01, -1

In [32]:
weight_tensor

<tf.Tensor: shape=(1, 3, 3, 32), dtype=float32, numpy=
array([[[[-9.15259957e-01,  6.11176670e-01, -4.27415752e+00,
          -2.29328966e+00, -1.44080076e+01,  3.96923482e-01,
          -8.07463586e-01, -1.21548533e+00,  1.08540905e+00,
           1.34548079e-02, -3.46037060e-01,  2.82633245e-01,
          -7.18247294e-01, -5.29765964e-01, -3.96382093e-01,
           1.12900615e+00, -8.88921618e-01,  1.52252108e-01,
          -1.59450328e+00,  4.35953915e-01, -1.89245164e-01,
          -2.97230315e+00,  8.35833073e-01,  2.05819201e+00,
          -3.63298029e-01,  2.63530284e-01,  3.67984384e-01,
           2.48542523e+00,  1.84968680e-01, -2.58495331e+00,
          -1.10956693e+00, -4.70633954e-02],
         [-7.10666895e+00,  3.58766937e+00, -1.20936143e+00,
          -2.95472074e+00, -2.37228703e+00,  5.35582006e-01,
          -7.91666806e-01, -9.66980159e-01,  3.81039095e+00,
           1.16736233e+00, -1.72302499e-01,  3.80082816e-01,
          -6.09364152e-01, -5.31910360e-01, -1

In [28]:
alpha.shape

TensorShape([1, 1, 1, 32])

In [29]:
alpha

<tf.Tensor: shape=(1, 1, 1, 32), dtype=float32, numpy=
array([[[[ 0.10963849,  0.10314579,  0.22634086, 18.4899    ,
           0.1949603 ,  0.09603638,  0.32295808,  8.025716  ,
           0.16579953,  0.16577041,  0.12513469,  1.5417764 ,
          19.590965  , 20.824562  ,  0.10010293,  0.11848979,
           4.1989236 ,  0.14698507,  1.1974407 , 25.109558  ,
           0.04843626,  0.10568715,  0.3388922 ,  0.09340779,
           0.07629511,  0.26300952, -0.20090102,  0.09004723,
           1.1100543 ,  0.66884154,  0.2641704 ,  0.4004299 ]]]],
      dtype=float32)>

In [31]:
a = tf.constant([[1,1],[2,2],[3,4]])

In [32]:
a

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 1],
       [2, 2],
       [3, 4]], dtype=int32)>

In [36]:
b = tf.constant([[2,1]])

In [37]:
b

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[2, 1]], dtype=int32)>

In [38]:
a * b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [4, 2],
       [6, 4]], dtype=int32)>

In [39]:
weight_tensor.shape

TensorShape([1, 3, 3, 32])

In [40]:
alpha.shape

TensorShape([1, 1, 1, 32])

In [41]:
alpha

<tf.Tensor: shape=(1, 1, 1, 32), dtype=float32, numpy=
array([[[[ 0.10963849,  0.10314579,  0.22634086, 18.4899    ,
           0.1949603 ,  0.09603638,  0.32295808,  8.025716  ,
           0.16579953,  0.16577041,  0.12513469,  1.5417764 ,
          19.590965  , 20.824562  ,  0.10010293,  0.11848979,
           4.1989236 ,  0.14698507,  1.1974407 , 25.109558  ,
           0.04843626,  0.10568715,  0.3388922 ,  0.09340779,
           0.07629511,  0.26300952, -0.20090102,  0.09004723,
           1.1100543 ,  0.66884154,  0.2641704 ,  0.4004299 ]]]],
      dtype=float32)>

In [45]:
weight_tensor[0,0,1,:] * alpha

<tf.Tensor: shape=(1, 1, 1, 32), dtype=float32, numpy=
array([[[[-7.7916443e-01,  3.7005296e-01, -2.7372789e-01,
          -5.4632492e+01, -4.6250179e-01,  5.1435359e-02,
          -2.5567520e-01, -7.7607079e+00,  6.3176101e-01,
           1.9351414e-01, -2.1561021e-02,  5.8600271e-01,
          -1.1938032e+01, -1.1076800e+01, -1.2729524e-01,
          -1.2315797e-01, -4.8657784e+00, -5.3255524e-02,
          -1.0328590e+00,  2.4162693e+01, -4.2303052e-02,
          -1.2452856e+00,  3.6716223e-01,  1.8091552e-01,
          -1.9573931e+00, -2.0342417e+00, -3.8823951e-02,
           3.5917014e-01,  5.5014735e-01,  2.1783974e+00,
          -3.6086950e-01,  3.1154159e-01]]]], dtype=float32)>

In [50]:
weight_tensor[0,0,0,0] * alpha[0,0,0,0]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.10034772>

In [51]:
weight_tensor[0,0,0,0]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.91525996>

In [54]:
from torch import nn

In [56]:
m = nn.AvgPool2d(7, stride=1)

In [57]:
 i = torch.randn(1, 1280, 7, 7)

In [58]:
output = m(i)

In [60]:
output.shape

torch.Size([1, 1280, 1, 1])

### load tflite 

In [72]:
import numpy as np

In [63]:
inter = tf.lite.Interpreter(model_path = "/Users/bob/code/ByteDance/PNN/resource/models/mobilenet_v2_1.0_224.tflite")

In [65]:
inter.allocate_tensors()

In [66]:
input_details = inter.get_input_details()

In [67]:
outout_details = inter.get_output_details()

In [69]:
input_shape = input_details[0]['shape']

In [73]:
input_data = np.array(np.random.random_sample(input_shape),dtype=np.float32)

In [78]:
input_data.flatten().tofile("/Users/bob/code/ByteDance/PNN/resource/models/test_random_input_1_224_224_3.bin")

In [80]:
inter.set_tensor(input_details[0]['index'], input_data)

In [81]:
inter.invoke()

In [83]:
output_data = inter.get_tensor(outout_details[0]['index'])

In [86]:
output_data.flatten().tofile("/Users/bob/code/ByteDance/PNN/resource/models/test_standard_output.bin")

In [87]:
input_data.flatten()

array([0.63374734, 0.97214967, 0.2874241 , ..., 0.6608173 , 0.08425715,
       0.6965691 ], dtype=float32)

In [88]:
output_data.flatten()

array([1.2897396e-05, 8.4614248e-06, 2.1369009e-05, ..., 6.3716388e-06,
       2.8654251e-06, 1.8185686e-04], dtype=float32)

In [1]:
import tensorflow as tf

In [6]:
model = tf.keras.Sequential()

In [7]:
model.add(tf.keras.layers.Dense(32, input_shape=(500,)))

In [9]:
model.add(tf.keras.layers.BatchNormalization())

In [30]:
model.layers[1].get_weights()[3].shape

(32,)

In [2]:
print(tf.__version__)

2.4.0


In [9]:
tf.compat.v1.lite.TFLiteConverter.from_frozen_graph("/Users/bob/Desktop/deepfm.pb",["l1","l2","l3"],[])

ValueError: Input 1 of node embedding/embedding_lookup was passed float from C1:0 incompatible with expected int32.

In [10]:
a = b'\x80abc'

In [14]:
type(a)

bytes

In [13]:
a.

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte