In [1]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf

In [2]:
from tensorflow import keras

In [3]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from datetime import datetime
from packaging import version

In [4]:
print("TensorFlow version: ", tf.__version__)
assert version.parse(tf.__version__).release[0] >= 2, \
    "This notebook requires TensorFlow 2.0 or above."

TensorFlow version:  2.4.0


In [5]:
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(10, activation='softmax')
])

2022-03-29 16:04:14.685175: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-03-29 16:04:14.686198: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [6]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy'])

In [7]:
(train_images, train_labels), _ = keras.datasets.fashion_mnist.load_data()
train_images = train_images / 255.0

In [8]:
# Define the Keras TensorBoard callback.
logdir="./" + datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = keras.callbacks.TensorBoard(log_dir=logdir)

2022-03-29 16:04:15.681653: I tensorflow/core/profiler/lib/profiler_session.cc:136] Profiler session initializing.
2022-03-29 16:04:15.681671: I tensorflow/core/profiler/lib/profiler_session.cc:155] Profiler session started.
2022-03-29 16:04:15.681722: I tensorflow/core/profiler/lib/profiler_session.cc:172] Profiler session tear down.


In [9]:
# Train the model.
model.fit(
    train_images,
    train_labels, 
    batch_size=64,
    epochs=5, 
    callbacks=[tensorboard_callback])

2022-03-29 16:04:15.896086: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)


Epoch 1/5
211/938 [=====>........................] - ETA: 0s - loss: 1.3634 - accuracy: 0.5383

2022-03-29 16:04:16.258616: I tensorflow/core/profiler/lib/profiler_session.cc:136] Profiler session initializing.
2022-03-29 16:04:16.258633: I tensorflow/core/profiler/lib/profiler_session.cc:155] Profiler session started.
2022-03-29 16:04:16.261140: I tensorflow/core/profiler/lib/profiler_session.cc:71] Profiler session collecting data.
2022-03-29 16:04:16.268094: I tensorflow/core/profiler/lib/profiler_session.cc:172] Profiler session tear down.
2022-03-29 16:04:16.278392: I tensorflow/core/profiler/rpc/client/save_profile.cc:137] Creating directory: ./20220329-160415/train/plugins/profile/2022_03_29_16_04_16
2022-03-29 16:04:16.279361: I tensorflow/core/profiler/rpc/client/save_profile.cc:143] Dumped gzipped tool data for trace.json.gz to ./20220329-160415/train/plugins/profile/2022_03_29_16_04_16/lms.trace.json.gz
2022-03-29 16:04:16.286067: I tensorflow/core/profiler/rpc/client/save_profile.cc:137] Creating directory: ./20220329-160415/train/plugins/profile/2022_03_29_16_04_16
2

938/938 [==============================] - 1s 739us/step - loss: 0.9402 - accuracy: 0.6772
Epoch 2/5
938/938 [==============================] - 1s 708us/step - loss: 0.5064 - accuracy: 0.8230
Epoch 3/5
938/938 [==============================] - 1s 690us/step - loss: 0.4585 - accuracy: 0.8360
Epoch 4/5
938/938 [==============================] - 1s 737us/step - loss: 0.4384 - accuracy: 0.8432
Epoch 5/5
938/938 [==============================] - 1s 688us/step - loss: 0.4149 - accuracy: 0.8506


In [10]:
x = tf.Variable(3.0)

In [11]:
with tf.GradientTape() as tape:
    y = x**2

In [12]:
dy_dx = tape.gradient(y, x)
dy_dx.numpy()

6.0

### Pytorch

In [13]:
import torch

In [14]:
x = torch.tensor([0.5, 0.75], requires_grad=True)

In [15]:
y = torch.tensor([3], requires_grad=False)

In [16]:
z = x+y

In [17]:
x.grad_fn

In [18]:
z.grad_fn

In [19]:
z.backward(torch.tensor([1,1]))

In [20]:
z.requires_grad

True

In [21]:
import math

In [22]:

a = torch.Tensor([2.0])
b = torch.Tensor([math.pi/3])
x = torch.Tensor([math.pi])

y = torch.sin(a * x + b)

In [23]:
y

tensor([0.8660])

In [34]:
import tensorflow.compat.v1 as tf
from tensorflow.python.framework.ops import get_gradient_function

In [35]:
foo = tf.constant([[1,2],[3,4]],dtype=tf.float32)

In [36]:
foo

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [37]:
a = tf.shape(foo, name="shape")

In [39]:
ult = tf.get_default_graph().get_operation_by_name('shape')

KeyError: "The name 'shape' refers to an Operation not in the graph."

In [1]:
import torch