In [1]:
#!/usr/bin/env python3
# _*_ coding: utf-8 _*_

import sys

sys.path.append("../..")

In [2]:
from d2l import d2l_cn as d2l

In [3]:
import tensorflow as tf

In [4]:
tf.__version__

'2.0.0'

In [5]:
import torch

In [6]:
import numpy as np

In [18]:
source = np.asarray([
            1, 2, -1, 1, 3, 4, -2, 2,
            2, 1, 1, 2, 3, 4, -2, 2,
            3, 2, -1, 1, 3, 1, -2, 2,
            2, 1, 1, 2,  3, 4, -3, 2],dtype=np.float32)

In [19]:
source = tf.convert_to_tensor(source,dtype=np.float32)

In [20]:
source

<tf.Tensor: id=30, shape=(32,), dtype=float32, numpy=
array([ 1.,  2., -1.,  1.,  3.,  4., -2.,  2.,  2.,  1.,  1.,  2.,  3.,
        4., -2.,  2.,  3.,  2., -1.,  1.,  3.,  1., -2.,  2.,  2.,  1.,
        1.,  2.,  3.,  4., -3.,  2.], dtype=float32)>

In [21]:
source = tf.reshape(source,[2,2,2,4])

In [22]:
source

<tf.Tensor: id=32, shape=(2, 2, 2, 4), dtype=float32, numpy=
array([[[[ 1.,  2., -1.,  1.],
         [ 3.,  4., -2.,  2.]],

        [[ 2.,  1.,  1.,  2.],
         [ 3.,  4., -2.,  2.]]],


       [[[ 3.,  2., -1.,  1.],
         [ 3.,  1., -2.,  2.]],

        [[ 2.,  1.,  1.,  2.],
         [ 3.,  4., -3.,  2.]]]], dtype=float32)>

In [25]:
ln = tf.keras.layers.LayerNormalization(axis=-2,epsilon=1e-5)

In [26]:
ln(source)

<tf.Tensor: id=104, shape=(2, 2, 2, 4), dtype=float32, numpy=
array([[[[-0.99999493, -0.9999949 ,  0.99997985, -0.99997985],
         [ 0.9999949 ,  0.999995  , -0.99998   ,  0.99998   ]],

        [[-0.99997973, -0.9999977 ,  0.99999774,  0.        ],
         [ 0.99998   ,  0.99999774, -0.99999774,  0.        ]]],


       [[[ 0.        ,  0.99998   ,  0.99997985, -0.99997985],
         [ 0.        , -0.99997985, -0.99998   ,  0.99998   ]],

        [[-0.99997973, -0.9999977 ,  0.9999986 ,  0.        ],
         [ 0.99998   ,  0.99999774, -0.9999987 ,  0.        ]]]],
      dtype=float32)>

In [28]:
ln_1 = tf.keras.layers.LayerNormalization(axis=-3,epsilon=1e-5)

In [30]:
res = ln_1(source)

In [32]:
res

<tf.Tensor: id=162, shape=(2, 2, 2, 4), dtype=float32, numpy=
array([[[[-0.99997985,  0.99998   , -0.99999493, -0.99997985],
         [ 0.        ,  0.        ,  0.        ,  0.        ]],

        [[ 0.99998   , -0.99997985,  0.99999493,  0.99998   ],
         [ 0.        ,  0.        ,  0.        ,  0.        ]]],


       [[[ 0.99998   ,  0.99998   , -0.99999493, -0.99997985],
         [ 0.        , -0.9999977 ,  0.99997973,  0.        ]],

        [[-0.99997973, -0.99997985,  0.99999493,  0.99998   ],
         [ 0.        ,  0.99999774, -0.99998   ,  0.        ]]]],
      dtype=float32)>

In [34]:
res.numpy().flatten()

array([-0.99997985,  0.99998   , -0.99999493, -0.99997985,  0.        ,
        0.        ,  0.        ,  0.        ,  0.99998   , -0.99997985,
        0.99999493,  0.99998   ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.99998   ,  0.99998   , -0.99999493, -0.99997985,
        0.        , -0.9999977 ,  0.99997973,  0.        , -0.99997973,
       -0.99997985,  0.99999493,  0.99998   ,  0.        ,  0.99999774,
       -0.99998   ,  0.        ], dtype=float32)