In [1]:
import numpy as np
np_load_old = np.load

# modify the default parameters of np.load
np.load = lambda *a,**k: np_load_old(*a, allow_pickle=True, **k)

In [2]:
import tensorflow as tf

In [3]:
np_input = np.load("/Users/bob/docs/ByteDance/espresso/bert语音模型/task_input.npy")

In [4]:
np_arr = np_input.item()['src_tokens']

In [5]:
np_arr.shape

(1, 1, 1035, 80)

In [6]:
np_output = np.load("/Users/bob/docs/ByteDance/espresso/bert语音模型/task_output.npy")

In [7]:
np_output.shape

(259, 365, 1)

In [8]:
np_output[0,0,0]

-2.79738

In [9]:
np_output

array([[[-2.79738  ],
        [-3.4349728],
        [-2.8072953],
        ...,
        [-3.2976322],
        [-2.8735304],
        [19.57089  ]],

       [[-3.429833 ],
        [-4.1716685],
        [-3.5441985],
        ...,
        [-3.7744877],
        [-3.2619812],
        [20.053272 ]],

       [[-3.3450122],
        [-4.140708 ],
        [-3.5107887],
        ...,
        [-3.720094 ],
        [-3.1962402],
        [21.238876 ]],

       ...,

       [[-3.4010704],
        [-4.1311517],
        [-3.4937804],
        ...,
        [-3.676906 ],
        [-3.205554 ],
        [20.92643  ]],

       [[-3.3726852],
        [-4.092108 ],
        [-3.4722443],
        ...,
        [-3.6262994],
        [-3.1819704],
        [20.849691 ]],

       [[-3.2890878],
        [-3.7752538],
        [-3.212875 ],
        ...,
        [-3.4127398],
        [-3.0322008],
        [20.083883 ]]], dtype=float32)

In [10]:
input_tf = tf.convert_to_tensor(np_arr)

In [11]:
input_tf

<tf.Tensor: id=0, shape=(1, 1, 1035, 80), dtype=float32, numpy=
array([[[[1.25762602e+05, 4.55268906e+05, 1.09248238e+06, ...,
          2.24462866e+03, 2.28380957e+03, 1.59074036e+03],
         [3.47812266e+04, 1.25910336e+05, 6.75793984e+04, ...,
          1.41818677e+03, 1.60462073e+03, 2.04070081e+03],
         [1.28189951e+04, 4.64056055e+04, 1.08342510e+04, ...,
          1.20898462e+03, 1.11889746e+03, 1.23886829e+03],
         ...,
         [3.42566589e+02, 1.24011365e+03, 6.15149072e+03, ...,
          4.00663666e+02, 9.11805847e+02, 2.36981476e+02],
         [3.37475166e+01, 1.22168243e+02, 2.26967212e+03, ...,
          2.71180603e+02, 7.58971619e+02, 8.54325806e+02],
         [3.58467560e+02, 1.29767627e+03, 3.36008110e+01, ...,
          4.74133209e+02, 2.10968918e+02, 7.68129944e+02]]]],
      dtype=float32)>

In [12]:
nhwc_input_tf = tf.transpose(input_tf,[0, 2, 3, 1])

In [13]:
nhwc_input_tf

<tf.Tensor: id=2, shape=(1, 1035, 80, 1), dtype=float32, numpy=
array([[[[1.25762602e+05],
         [4.55268906e+05],
         [1.09248238e+06],
         ...,
         [2.24462866e+03],
         [2.28380957e+03],
         [1.59074036e+03]],

        [[3.47812266e+04],
         [1.25910336e+05],
         [6.75793984e+04],
         ...,
         [1.41818677e+03],
         [1.60462073e+03],
         [2.04070081e+03]],

        [[1.28189951e+04],
         [4.64056055e+04],
         [1.08342510e+04],
         ...,
         [1.20898462e+03],
         [1.11889746e+03],
         [1.23886829e+03]],

        ...,

        [[3.42566589e+02],
         [1.24011365e+03],
         [6.15149072e+03],
         ...,
         [4.00663666e+02],
         [9.11805847e+02],
         [2.36981476e+02]],

        [[3.37475166e+01],
         [1.22168243e+02],
         [2.26967212e+03],
         ...,
         [2.71180603e+02],
         [7.58971619e+02],
         [8.54325806e+02]],

        [[3.58467560e+02],
     

In [14]:
nhwc_np = nhwc_input_tf.numpy()

In [15]:
nhwc_np

array([[[[1.25762602e+05],
         [4.55268906e+05],
         [1.09248238e+06],
         ...,
         [2.24462866e+03],
         [2.28380957e+03],
         [1.59074036e+03]],

        [[3.47812266e+04],
         [1.25910336e+05],
         [6.75793984e+04],
         ...,
         [1.41818677e+03],
         [1.60462073e+03],
         [2.04070081e+03]],

        [[1.28189951e+04],
         [4.64056055e+04],
         [1.08342510e+04],
         ...,
         [1.20898462e+03],
         [1.11889746e+03],
         [1.23886829e+03]],

        ...,

        [[3.42566589e+02],
         [1.24011365e+03],
         [6.15149072e+03],
         ...,
         [4.00663666e+02],
         [9.11805847e+02],
         [2.36981476e+02]],

        [[3.37475166e+01],
         [1.22168243e+02],
         [2.26967212e+03],
         ...,
         [2.71180603e+02],
         [7.58971619e+02],
         [8.54325806e+02]],

        [[3.58467560e+02],
         [1.29767627e+03],
         [3.36008110e+01],
         ...,
 

np.savetxt("input.txt",nhwc_np.flatten())

fw = open("input_data.txt","w")
with open("input.txt","r") as f:
    lines = f.readlines();
    for line in lines:
        new_line = line.replace('\n','')
        new_line = new_line + r',' + '\n'
        fw.write(new_line)

In [16]:
np_output[0,0,0]

-2.79738

In [17]:
for i in range(10):
    print(np_output[0,i,0])

-2.79738
-3.4349728
-2.8072953
-2.7529569
-2.9176917
-2.5937123
-2.9921324
-2.829307
-3.4564724
-3.0959613


In [18]:
input_tf.shape

TensorShape([1, 1, 1035, 80])

In [19]:
input_tf.numpy()

array([[[[1.25762602e+05, 4.55268906e+05, 1.09248238e+06, ...,
          2.24462866e+03, 2.28380957e+03, 1.59074036e+03],
         [3.47812266e+04, 1.25910336e+05, 6.75793984e+04, ...,
          1.41818677e+03, 1.60462073e+03, 2.04070081e+03],
         [1.28189951e+04, 4.64056055e+04, 1.08342510e+04, ...,
          1.20898462e+03, 1.11889746e+03, 1.23886829e+03],
         ...,
         [3.42566589e+02, 1.24011365e+03, 6.15149072e+03, ...,
          4.00663666e+02, 9.11805847e+02, 2.36981476e+02],
         [3.37475166e+01, 1.22168243e+02, 2.26967212e+03, ...,
          2.71180603e+02, 7.58971619e+02, 8.54325806e+02],
         [3.58467560e+02, 1.29767627e+03, 3.36008110e+01, ...,
          4.74133209e+02, 2.10968918e+02, 7.68129944e+02]]]],
      dtype=float32)

In [21]:
flatten_output = np_output.flatten()
for i in range(100):
    print(flatten_output[i])

-2.79738
-3.4349728
-2.8072953
-2.7529569
-2.9176917
-2.5937123
-2.9921324
-2.829307
-3.4564724
-3.0959613
4.0753984
-3.1662552
-2.505514
-2.8455827
-2.8732767
-1.6529224
-6.3917875
-2.2620463
-3.108081
4.298729
-2.1619928
2.2409892
2.149142
1.257595
-8.99403
-0.27971876
-2.7072163
-3.0040417
-3.3724318
-2.643643
-2.9943871
0.31761956
-2.914155
-5.7642508
-3.1165388
5.4563274
0.5856713
3.9974344
-2.709906
0.20105597
-2.733605
0.40190578
-3.1328635
-2.7355533
-2.4227076
-3.1506178
-3.402371
6.039572
3.7430549
3.4454503
5.325312
5.585564
-5.418111
2.2560487
0.43129987
-1.1704848
-3.8578186
-1.9741751
-2.7255766
-2.6671982
-2.7909856
-3.3161666
-3.0152507
-0.42805776
-4.649391
-4.300238
-2.6236944
4.296343
-6.05145
1.3562549
-0.33236337
0.58398426
-5.888913
-2.1493607
-2.8183544
-3.2411797
-2.67486
-2.9340637
-3.2669644
0.0015812516
-4.611634
-12.176823
-3.1568022
2.9637177
1.4699599
-0.17971207
-2.860958
-3.9235368
-9.957354
-4.401741
-2.7727609
-2.383861
-2.5552084
-3.2210808
-2.7411754

In [27]:
def foo():
    print(b)

In [28]:
foo()

NameError: name 'b' is not defined

In [29]:
b = 1

In [30]:
foo()

1


In [31]:
float("0.1")

0.1

In [32]:
a = "12"

In [33]:
b = "12"

In [34]:
a == b

True

In [35]:
str(-1.0)

'-1.0'