In [3]:
import torch

In [4]:
a = torch.tensor([[1,2,3],[4,5,6]])

In [5]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
torch.gather(a,1,torch.tensor([[0,0],[0,1]]))

tensor([[1, 1],
        [4, 5]])

In [7]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
a.view(-1,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [9]:
b = torch.tensor([1,2,3])

In [10]:
b

tensor([1, 2, 3])

In [11]:
b.size()

torch.Size([3])

In [12]:
b.shape

torch.Size([3])

In [13]:
b.shape

torch.Size([3])

In [14]:
b.view(-1,1)

tensor([[1],
        [2],
        [3]])

In [39]:
import tensorflow as tf
import numpy as np

In [47]:
data = tf.constant(np.array([
                [[[1,2,-1,1],[3,4,-2,2]],
                [[2,1,1,2],[3,4,-2,2]]],

                [[[3, 2, -1, 1], [3, 1, -2, 2]],
                 [[2, 1, 1, 2], [3, 4, -3, 2]]],
                ]), dtype=tf.float32)

In [48]:
data

<tf.Tensor: id=178, shape=(2, 2, 2, 4), dtype=float32, numpy=
array([[[[ 1.,  2., -1.,  1.],
         [ 3.,  4., -2.,  2.]],

        [[ 2.,  1.,  1.,  2.],
         [ 3.,  4., -2.,  2.]]],


       [[[ 3.,  2., -1.,  1.],
         [ 3.,  1., -2.,  2.]],

        [[ 2.,  1.,  1.,  2.],
         [ 3.,  4., -3.,  2.]]]], dtype=float32)>

In [49]:
layer = tf.keras.layers.LayerNormalization(axis=2)

In [50]:
output = layer(data)

In [51]:
output

<tf.Tensor: id=216, shape=(2, 2, 2, 4), dtype=float32, numpy=
array([[[[-0.99950033, -0.9995004 ,  0.99800587, -0.99800587],
         [ 0.9995004 ,  0.9995003 , -0.99800587,  0.99800587]],

        [[-0.99800587, -0.999778  ,  0.9997779 ,  0.        ],
         [ 0.99800587,  0.9997779 , -0.9997779 ,  0.        ]]],


       [[[ 0.        ,  0.99800587,  0.99800587, -0.99800587],
         [ 0.        , -0.99800587, -0.99800587,  0.99800587]],

        [[-0.99800587, -0.999778  ,  0.99987507,  0.        ],
         [ 0.99800587,  0.9997779 , -0.99987507,  0.        ]]]],
      dtype=float32)>

In [20]:
X = tf.constant([
                [[[1,2,-1,1],[3,4,-2,2]],
                [[2,1,1,2],[3,4,-2,2]]],

                [[[3, 2, -1, 1], [3, 1, -2, 2]],
                 [[2, 1, 1, 2], [3, 4, -3, 2]]],
                ],dtype=tf.float32)

In [21]:
layer = tf.keras.layers.LayerNormalization(axis=[1,2,3])

In [22]:
Y = layer(X)

In [23]:
Y

<tf.Tensor: id=78, shape=(2, 2, 2, 4), dtype=float32, numpy=
array([[[[-0.24760252,  0.31834614, -1.3794999 , -0.24760252],
         [ 0.88429475,  1.4502435 , -1.9454485 ,  0.31834614]],

        [[ 0.31834614, -0.24760252, -0.24760252,  0.31834614],
         [ 0.88429475,  1.4502435 , -1.9454485 ,  0.31834614]]],


       [[[ 0.9232424 ,  0.37613577, -1.2651839 , -0.1709708 ],
         [ 0.9232424 , -0.1709708 , -1.8122904 ,  0.37613577]],

        [[ 0.37613577, -0.1709708 , -0.1709708 ,  0.37613577],
         [ 0.9232424 ,  1.4703488 , -2.3593972 ,  0.37613577]]]],
      dtype=float32)>

In [24]:
layer2 = tf.keras.layers.LayerNormalization(axis=[2])

In [25]:
YY = layer2(X)

In [26]:
YY

<tf.Tensor: id=116, shape=(2, 2, 2, 4), dtype=float32, numpy=
array([[[[-0.99950033, -0.9995004 ,  0.99800587, -0.99800587],
         [ 0.9995004 ,  0.9995003 , -0.99800587,  0.99800587]],

        [[-0.99800587, -0.999778  ,  0.9997779 ,  0.        ],
         [ 0.99800587,  0.9997779 , -0.9997779 ,  0.        ]]],


       [[[ 0.        ,  0.99800587,  0.99800587, -0.99800587],
         [ 0.        , -0.99800587, -0.99800587,  0.99800587]],

        [[-0.99800587, -0.999778  ,  0.99987507,  0.        ],
         [ 0.99800587,  0.9997779 , -0.99987507,  0.        ]]]],
      dtype=float32)>

In [27]:
XX = tf.constant([
                [[[1,2,-1,1],[7,4,-2,2]],
                [[2,1,2,2],[1,4,-2,2]]],

                [[[9, 2, -4, 1], [3, 1, -2, 2]],
                 [[2, 1, 1, 2], [3, 5, -3, 2]]],
                ],dtype=tf.float32)

In [28]:
XXX = layer2(XX)

In [29]:
XXX

<tf.Tensor: id=137, shape=(2, 2, 2, 4), dtype=float32, numpy=
array([[[[-0.99994445, -0.9995004 ,  0.99800587, -0.99800587],
         [ 0.9999443 ,  0.9995003 , -0.99800587,  0.99800587]],

        [[ 0.99800587, -0.999778  ,  0.99987507,  0.        ],
         [-0.99800587,  0.9997779 , -0.99987507,  0.        ]]],


       [[[ 0.99994445,  0.99800587, -0.9995003 , -0.99800587],
         [-0.99994445, -0.99800587,  0.9995004 ,  0.99800587]],

        [[-0.99800587, -0.99987507,  0.99987507,  0.        ],
         [ 0.99800587,  0.99987507, -0.99987507,  0.        ]]]],
      dtype=float32)>

In [30]:
import torch.nn as nn

In [36]:
torch_x = torch.tensor([
                [[[1,2,-1,1],[3,4,-2,2]],
                [[2,1,1,2],[3,4,-2,2]]],

                [[[3, 2, -1, 1], [3, 1, -2, 2]],
                 [[2, 1, 1, 2], [3, 4, -3, 2]]],
                ],dtype=torch.float32)

In [34]:
ln = nn.LayerNorm((4),eps=0,elementwise_affine=False)

In [35]:
ln(tmp)

RuntimeError: Given normalized_shape=[2, 3], expected input with shape [*, 2, 3], but got input of size[2, 2, 3, 5]

In [ ]:
ln_2 = tf.keras.layers.LayerNormalization(axis=[2])