In [2]:
import torch

In [3]:
a = torch.tensor([[1,2,3],[4,5,6]])

In [4]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
torch.gather(a,1,torch.tensor([[0,0],[0,1]]))

tensor([[1, 1],
        [4, 5]])

In [6]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
a.view(-1,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [8]:
b = torch.tensor([1,2,3])

In [9]:
b

tensor([1, 2, 3])

In [10]:
b.size()

torch.Size([3])

In [11]:
b.shape

torch.Size([3])

In [12]:
b.shape

torch.Size([3])

In [13]:
b.view(-1,1)

tensor([[1],
        [2],
        [3]])

In [14]:
import tensorflow as tf
import numpy as np

In [15]:
data = tf.constant(np.array([
                [[[1,5,-1,1],[3,4,-2,10],[1,1,1,1],[3,4,5,6]],
                [[2,1,1,2],[3,4,-2,6],[2,2,2,2],[4,5,6,7]]],

                [[[3, 2, -1, 1], [3, 1, -2, 2],[3,3,3,3],[5,6,7,8]],
                 [[100, 7, 1, 2], [9, 4, -3, 2],[4,4,4,4],[6,7,8,9]]],
                ]), dtype=tf.float32)

In [16]:
data

<tf.Tensor: id=0, shape=(2, 2, 4, 4), dtype=float32, numpy=
array([[[[  1.,   5.,  -1.,   1.],
         [  3.,   4.,  -2.,  10.],
         [  1.,   1.,   1.,   1.],
         [  3.,   4.,   5.,   6.]],

        [[  2.,   1.,   1.,   2.],
         [  3.,   4.,  -2.,   6.],
         [  2.,   2.,   2.,   2.],
         [  4.,   5.,   6.,   7.]]],


       [[[  3.,   2.,  -1.,   1.],
         [  3.,   1.,  -2.,   2.],
         [  3.,   3.,   3.,   3.],
         [  5.,   6.,   7.,   8.]],

        [[100.,   7.,   1.,   2.],
         [  9.,   4.,  -3.,   2.],
         [  4.,   4.,   4.,   4.],
         [  6.,   7.,   8.,   9.]]]], dtype=float32)>

In [17]:
layer = tf.keras.layers.LayerNormalization(axis=2,epsilon=1e-5)

In [18]:
output = layer(data)

In [19]:
output

<tf.Tensor: id=39, shape=(2, 2, 4, 4), dtype=float32, numpy=
array([[[[-0.99999493,  0.9999976 , -0.6527529 , -0.9271723 ],
         [ 0.9999949 ,  0.33333254, -1.0257545 ,  1.4569851 ],
         [-0.99999493, -1.6666629 ,  0.09325039, -0.9271723 ],
         [ 0.9999949 ,  0.33333254,  1.5852568 ,  0.3973595 ]],

        [[-0.9045274 , -1.2649086 , -0.2621111 , -0.98787725],
         [ 0.30150914,  0.6324543 , -1.3105555 ,  0.76834893],
         [-0.9045274 , -0.6324543 ,  0.08737034, -0.98787725],
         [ 1.5075457 ,  1.2649087 ,  1.485296  ,  1.2074056 ]]],


       [[[-0.5773463 , -0.5345217 , -0.77204835, -0.92847604],
         [-0.5773463 , -1.0690434 , -1.0527933 , -0.55708563],
         [-0.5773463 ,  0.        ,  0.35093105, -0.18569517],
         [ 1.732039  ,  1.6035651 ,  1.4739106 ,  1.6712568 ]],

        [[ 1.7303863 ,  0.99999785, -0.3721041 , -0.78633326],
         [-0.5111105 , -0.9999976 , -1.3643818 , -0.78633326],
         [-0.63426965, -0.9999976 ,  0.3721041 , 

In [40]:
X = tf.constant([
                [[[1,2,-1,1],[3,4,-2,2]],
                [[2,1,1,2],[3,4,-2,2]]],

                [[[3, 2, -1, 1], [3, 1, -2, 2]],
                 [[2, 1, 1, 2], [3, 4, -3, 2]]],
                ],dtype=tf.float32)

In [41]:
layer = tf.keras.layers.LayerNormalization(axis=[2])

In [42]:
Y = layer(X)

In [43]:
Y

<tf.Tensor: id=176, shape=(2, 2, 2, 4), dtype=float32, numpy=
array([[[[-0.99950033, -0.9995004 ,  0.99800587, -0.99800587],
         [ 0.9995004 ,  0.9995003 , -0.99800587,  0.99800587]],

        [[-0.99800587, -0.999778  ,  0.9997779 ,  0.        ],
         [ 0.99800587,  0.9997779 , -0.9997779 ,  0.        ]]],


       [[[ 0.        ,  0.99800587,  0.99800587, -0.99800587],
         [ 0.        , -0.99800587, -0.99800587,  0.99800587]],

        [[-0.99800587, -0.999778  ,  0.99987507,  0.        ],
         [ 0.99800587,  0.9997779 , -0.99987507,  0.        ]]]],
      dtype=float32)>

In [44]:
layer2 = tf.keras.layers.LayerNormalization(axis=[2])

In [45]:
YY = layer2(X)

In [46]:
YY

<tf.Tensor: id=214, shape=(2, 2, 2, 4), dtype=float32, numpy=
array([[[[-0.99950033, -0.9995004 ,  0.99800587, -0.99800587],
         [ 0.9995004 ,  0.9995003 , -0.99800587,  0.99800587]],

        [[-0.99800587, -0.999778  ,  0.9997779 ,  0.        ],
         [ 0.99800587,  0.9997779 , -0.9997779 ,  0.        ]]],


       [[[ 0.        ,  0.99800587,  0.99800587, -0.99800587],
         [ 0.        , -0.99800587, -0.99800587,  0.99800587]],

        [[-0.99800587, -0.999778  ,  0.99987507,  0.        ],
         [ 0.99800587,  0.9997779 , -0.99987507,  0.        ]]]],
      dtype=float32)>

In [27]:
XX = tf.constant([
                [[[1,2,-1,1],[7,4,-2,2]],
                [[2,1,2,2],[1,4,-2,2]]],

                [[[9, 2, -4, 1], [3, 1, -2, 2]],
                 [[2, 1, 1, 2], [3, 5, -3, 2]]],
                ],dtype=tf.float32)

In [28]:
XXX = layer2(XX)

In [29]:
XXX

<tf.Tensor: id=137, shape=(2, 2, 2, 4), dtype=float32, numpy=
array([[[[-0.99994445, -0.9995004 ,  0.99800587, -0.99800587],
         [ 0.9999443 ,  0.9995003 , -0.99800587,  0.99800587]],

        [[ 0.99800587, -0.999778  ,  0.99987507,  0.        ],
         [-0.99800587,  0.9997779 , -0.99987507,  0.        ]]],


       [[[ 0.99994445,  0.99800587, -0.9995003 , -0.99800587],
         [-0.99994445, -0.99800587,  0.9995004 ,  0.99800587]],

        [[-0.99800587, -0.99987507,  0.99987507,  0.        ],
         [ 0.99800587,  0.99987507, -0.99987507,  0.        ]]]],
      dtype=float32)>

In [30]:
import torch.nn as nn

In [31]:
torch_x = torch.tensor([
                [[[1,2,-1,1],[3,4,-2,2]],
                [[2,1,1,2],[3,4,-2,2]]],

                [[[3, 2, -1, 1], [3, 1, -2, 2]],
                 [[2, 1, 1, 2], [3, 4, -3, 2]]],
                ],dtype=torch.float32)

In [32]:
ln = nn.LayerNorm((4),eps=0,elementwise_affine=False)

In [33]:
torch.set_printoptions(profile="full")

In [34]:
tensor = torch.rand((1,20,20,5),dtype=torch.float32)*100

In [35]:
tensor

tensor([[[[7.7165e+01, 7.3663e-01, 4.2904e+01, 5.8010e+01, 6.4828e+01],
          [3.7556e+01, 8.8685e+01, 2.0674e+01, 5.7003e+01, 6.9975e-01],
          [9.0135e+01, 2.7283e+01, 3.7194e+01, 8.1876e+01, 8.3222e+01],
          [2.7664e+01, 7.8320e+01, 2.1150e+01, 7.8157e+01, 9.8200e+01],
          [4.8822e+01, 1.4980e+01, 1.9224e+01, 8.0273e+01, 8.3104e+01],
          [9.4541e+01, 2.1030e+01, 7.1607e+01, 7.5986e+01, 1.6248e+01],
          [6.3227e+01, 1.2347e+01, 9.8504e+01, 1.1366e+01, 4.5871e+01],
          [2.7110e+01, 3.5107e+01, 4.2266e+00, 3.4952e+01, 4.9234e+01],
          [7.8114e+01, 3.0466e+01, 5.6701e+01, 1.3761e+01, 3.1506e+01],
          [4.0274e+01, 2.1818e+01, 9.4640e+01, 2.3044e+01, 3.3030e+01],
          [2.2225e+01, 9.4089e+01, 6.8445e+01, 5.8831e+01, 3.9944e+01],
          [9.6444e+01, 5.6063e+01, 3.1359e+01, 7.8062e+01, 7.2536e+01],
          [8.7296e+01, 6.8963e+01, 1.3287e+01, 1.0537e+01, 9.0258e+01],
          [6.0752e+01, 7.4380e+01, 6.5421e+01, 5.4726e+01, 6.837

In [36]:
tensor.numel()

2000

In [37]:
pp = torch.mean(tensor,dim=2)

In [38]:
pp

tensor([[[56.5267, 43.3027, 45.0089, 51.2381, 56.0624],
         [52.3587, 47.5104, 43.2412, 51.7901, 50.1637],
         [51.2627, 50.0543, 52.1700, 64.6698, 35.0476],
         [52.0398, 58.7170, 54.0607, 55.6362, 53.3038],
         [50.6981, 49.2558, 56.6490, 49.0840, 53.6890],
         [49.0107, 51.6062, 55.5943, 59.6759, 53.2908],
         [56.7459, 53.1672, 52.6439, 51.6755, 47.8517],
         [42.5570, 53.5420, 46.8436, 59.0476, 43.2961],
         [50.0486, 39.9470, 50.0093, 52.9845, 53.7666],
         [45.2397, 51.6227, 40.4288, 44.9813, 58.1564],
         [50.1134, 51.9325, 51.8540, 46.2420, 48.1207],
         [57.3500, 50.6294, 44.1939, 46.4929, 49.6760],
         [56.3839, 46.8750, 62.6101, 57.8470, 42.8351],
         [64.4257, 52.4420, 52.8826, 44.6204, 61.3808],
         [43.6799, 49.5667, 54.6221, 35.7827, 47.9661],
         [43.7722, 46.4101, 44.4377, 53.6880, 44.9365],
         [49.7197, 63.9406, 51.7437, 49.0584, 62.2208],
         [44.7330, 46.8733, 45.6486, 64.4152, 44

In [39]:
pp.numel()

100