In [6]:
import torch

In [7]:
a = torch.tensor([[1,2,3],[4,5,6]])

In [8]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
torch.gather(a,1,torch.tensor([[0,0],[0,1]]))

tensor([[1, 1],
        [4, 5]])

In [10]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
a.view(-1,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [12]:
b = torch.tensor([1,2,3])

In [13]:
b

tensor([1, 2, 3])

In [14]:
b.size()

torch.Size([3])

In [15]:
b.shape()

TypeError: 'torch.Size' object is not callable

In [16]:
b.shape

torch.Size([3])

In [17]:
b.view(-1,1)

tensor([[1],
        [2],
        [3]])