In [1]:
import torch.nn as nn

In [2]:
import torch
import torchvision.utils as vutil
import matplotlib.pyplot as plt
import numpy as np

torch.set_printoptions(precision=9,sci_mode=False)

### 无Padding3D卷积

In [3]:
conv3d = nn.Conv3d(3,6,(2,2,2),stride = (2,2,2), padding = (0,0,0))

In [4]:
conv3d

Conv3d(3, 6, kernel_size=(2, 2, 2), stride=(2, 2, 2))

In [5]:
inpu = torch.randn(2,3,4,4,4) #nchw 输入

In [107]:
ndhwc_inpu = inpu.permute(0,2,3,4,1)

In [91]:
output = conv3d(inpu)#无padding 3D卷积结果 2,6,2,2,2

In [92]:
ndhwc_oo = output.permute(0,2,3,4,1).flatten()#输出的ndhwc

In [93]:
ndhwc_oo

tensor([ 0.400361001,  0.818243861, -0.431531399,  0.203201652,  0.228223562,
         0.912180722, -1.421884060,  0.029091567,  0.664748311,  0.127266288,
        -0.931493282,  0.153248370, -0.176201582,  0.429376990, -0.037033573,
        -0.653678834, -0.716092944, -0.380999982,  0.803049445,  0.199668020,
         1.225344539, -0.015932791,  0.649916232, -0.582836747,  0.101251408,
         0.870635867, -1.140085578, -0.877479970, -0.438286215,  0.763333619,
        -0.496566713, -0.231463090, -1.002908945, -0.183172673, -0.490460783,
         0.273453653, -1.353447914,  0.005253088, -0.040447071, -0.401420653,
         0.113098629, -0.262295753, -0.008534640, -0.423417330,  0.362395167,
         0.001570784, -0.670651913,  0.163725346, -0.283487141,  0.063316971,
        -0.078043014, -0.350190699,  0.204402715,  0.173307762,  0.015054479,
         0.012090363,  1.306453228,  0.007401265,  0.411136001,  0.545184135,
        -0.353445828,  0.413575500, -0.405857414,  0.075647481, 

In [94]:
t_weight = conv3d.weight.detach()

In [98]:
t_weight.permute(0,2,3,4,1).flatten()

tensor([-0.197163165, -0.040623769,  0.004565284,  0.117050111,  0.154201716,
        -0.029594317, -0.088743091,  0.014015630, -0.146285594, -0.190658599,
        -0.034835830,  0.190556586,  0.001574248, -0.106620200,  0.043782070,
        -0.199941814,  0.014647692,  0.047040164, -0.123105802, -0.172810838,
         0.088828862, -0.187406823,  0.012307808, -0.081229173,  0.151385635,
         0.161474675, -0.114548519,  0.150489658, -0.202933028,  0.016262859,
         0.025245637, -0.028960273, -0.011759788, -0.065309256, -0.043390632,
         0.100476742,  0.132423967, -0.132208854, -0.064791098, -0.118203796,
        -0.148075402, -0.174942598,  0.043807834,  0.107447028, -0.023169354,
         0.047150433, -0.156879723,  0.093154013, -0.090936996, -0.154037952,
        -0.042358994,  0.012844235,  0.151275516, -0.193146363, -0.141823441,
        -0.177645907,  0.157371879, -0.159473404, -0.154849365,  0.153597593,
         0.061874241,  0.045664087, -0.046172127, -0.198500052, 

In [152]:
conv3d_bias.flatten()

tensor([-0.159271732, -0.026359349,  0.121022493, -0.090112217, -0.086764120,
         0.123217165])

In [160]:
ndhwc_oo[0:49]

tensor([ 0.400361001,  0.818243861, -0.431531399,  0.203201652,  0.228223562,
         0.912180722, -1.421884060,  0.029091567,  0.664748311,  0.127266288,
        -0.931493282,  0.153248370, -0.176201582,  0.429376990, -0.037033573,
        -0.653678834, -0.716092944, -0.380999982,  0.803049445,  0.199668020,
         1.225344539, -0.015932791,  0.649916232, -0.582836747,  0.101251408,
         0.870635867, -1.140085578, -0.877479970, -0.438286215,  0.763333619,
        -0.496566713, -0.231463090, -1.002908945, -0.183172673, -0.490460783,
         0.273453653, -1.353447914,  0.005253088, -0.040447071, -0.401420653,
         0.113098629, -0.262295753, -0.008534640, -0.423417330,  0.362395167,
         0.001570784, -0.670651913,  0.163725346, -0.283487141],
       grad_fn=<SliceBackward>)

In [121]:
output.flatten()[0:16]

tensor([ 0.400361001, -1.421884060, -0.176201582,  0.803049445,  0.101251408,
        -0.496566713, -1.353447914, -0.008534640,  0.818243861,  0.029091567,
         0.429376990,  0.199668020,  0.870635867, -0.231463090,  0.005253088,
        -0.423417330], grad_fn=<SliceBackward>)

In [125]:
#第一个元素
element_0 = inpu[0,:,0:2,0:2,0:2]
weight_0 = t_weight[0]

In [154]:
element_0.permute(1,2,3,0)

tensor([[[[-0.677477419,  0.855155885,  0.389280677],
          [ 1.701459169, -2.393318653, -0.659011781]],

         [[ 0.326830149,  0.590776384,  0.543837190],
          [-0.867203236,  0.997774780, -0.327538937]]],


        [[[ 1.820635915,  0.364208311,  1.013283730],
          [-0.631898463,  0.599438906, -0.120152950]],

         [[-1.435472250, -1.200431705,  0.878733575],
          [-0.521797895, -1.368958831,  0.486267745]]]])

In [161]:
inpu[1,:,0:2,0:2,0:2].permute(1,2,3,0)

tensor([[[[ 0.399538010,  0.486807793, -0.576265693],
          [-1.060873151,  0.178744495, -0.197793439]],

         [[ 1.527684808,  0.005218608,  0.649046600],
          [ 0.707829952,  0.701092303,  0.663221955]]],


        [[[-0.480633169, -1.419729948, -0.226728648],
          [-0.591771781,  0.412155330,  0.040993661]],

         [[-0.511895776,  0.983702719,  0.053600386],
          [-0.675211549,  0.574526906, -0.403750539]]]])

In [127]:
(element_0 * weight_0).sum() + conv3d.bias[0]

tensor(0.400361001, grad_fn=<AddBackward0>)

In [132]:
ndhwc_weight = t_weight.permute(0,2,3,4,1)

In [140]:
ndhwc_element_0 = ndhwc_inpu[0,0:2,0:2,0:2,:]
ndhwc_weight_0 = ndhwc_weight[0]

In [141]:
(ndhwc_element_0 * ndhwc_weight_0).sum() + conv3d.bias[0]

tensor(0.400361001, grad_fn=<AddBackward0>)

In [150]:
ndhwc_weight_0.flatten()

tensor([-0.197163165, -0.040623769,  0.004565284,  0.117050111,  0.154201716,
        -0.029594317, -0.088743091,  0.014015630, -0.146285594, -0.190658599,
        -0.034835830,  0.190556586,  0.001574248, -0.106620200,  0.043782070,
        -0.199941814,  0.014647692,  0.047040164, -0.123105802, -0.172810838,
         0.088828862, -0.187406823,  0.012307808, -0.081229173])

In [149]:
(ndhwc_element_0.flatten() * ndhwc_weight_0.flatten()).sum() + conv3d.bias[0]

tensor(0.400361061, grad_fn=<AddBackward0>)

#### 将conv3d的weight和bias导出为二进制权重文件-ByteNN

In [85]:
conv3d_weights_ndhwc = conv3d.weight.detach().permute(0,2,3,4,1).flatten()# 3d kernel shape (N,K_d,K_h,K_w,K_c) 6,3,2,2,2

In [86]:
conv3d_bias = conv3d.bias.detach()

In [87]:
conv3d_weights = torch.cat([conv3d_weights_ndhwc,conv3d_bias],0)
conv3d_weights.numpy().tofile("./3dconv_nopadding_6_3_2_2_2.bin")

In [89]:
ndhwc_inpu = inpu.permute(0,2,3,4,1)

In [90]:
ndhwc_inpu.flatten()

tensor([    -0.677477419,      0.855155885,      0.389280677,      1.701459169,
            -2.393318653,     -0.659011781,     -1.040668726,     -0.367632866,
            -1.158213735,     -1.238954186,     -1.043065548,      1.595522046,
             0.326830149,      0.590776384,      0.543837190,     -0.867203236,
             0.997774780,     -0.327538937,     -0.524605632,     -1.251438141,
             1.224642277,     -0.569253564,     -1.939467788,     -0.091128983,
             0.295207262,     -0.000667778,     -1.708417892,     -1.621702313,
            -0.689467847,     -0.489764214,      0.622125387,      0.493621558,
            -1.345140457,     -0.420483500,      0.956219912,      0.805260003,
             0.396177799,      1.728724957,     -0.640162945,     -1.327747583,
            -0.116186194,      1.416773200,     -1.171965718,     -1.176180363,
             0.039866891,     -1.349842548,     -2.317263842,      0.901690423,
             1.820635915,      0.3642083

#### 将conv3d导出为onnx格式

In [47]:
torch.onnx.export(conv3d, inpu, "conv3d.onnx", input_names=["data"], output_names=["output"], opset_version=9, verbose=True)

graph(%data : Float(2:192, 3:64, 4:16, 4:4, 4:1),
      %weight : Float(6:24, 3:8, 2:4, 2:2, 2:1),
      %bias : Float(6:1)):
  %output : Float(2:48, 6:8, 2:4, 2:2, 2:1) = onnx::Conv[dilations=[1, 1, 1], group=1, kernel_shape=[2, 2, 2], pads=[0, 0, 0, 0, 0, 0], strides=[2, 2, 2]](%data, %weight, %bias) # /opt/anaconda3/envs/d2l/lib/python3.7/site-packages/torch/nn/modules/conv.py:567:0
  return (%output)



### 带padding的3D卷积

In [12]:
p_conv3d =  nn.Conv3d(3, 6 , 2 , 2 , 1) #padding_3

In [13]:
p_conv3d

Conv3d(3, 6, kernel_size=(2, 2, 2), stride=(2, 2, 2), padding=(1, 1, 1))

In [44]:
output = p_conv3d(inpu)#2, 6, 3, 3, 3 ncdhw

In [45]:
output.shape

torch.Size([2, 6, 3, 3, 3])

In [46]:
output.permute(0,2,3,4,1).flatten() #ndhwc output

tensor([     0.189636603,     -0.026826985,     -0.145218715,      0.036691561,
             0.050017677,      0.280198872,      0.266377091,     -0.204123914,
            -0.154714823,     -0.175057679,     -0.177048445,      0.437328368,
            -0.476220369,     -0.066917360,     -0.204527959,      0.001488298,
            -0.429623842,     -0.070198476,     -0.317002475,     -0.201768935,
             0.407611132,     -0.000752002,     -0.047781300,      0.073053151,
            -0.786560833,     -0.211224943,     -0.232304603,     -0.265940368,
             0.114423841,      0.215479136,      0.145952523,     -0.235555500,
             0.282161653,     -0.033440381,      0.247457013,      0.162064791,
             0.035857596,      0.030584376,      0.250688732,      0.283859193,
            -0.450386047,     -0.305677354,      0.245224312,      0.064171419,
            -0.462553144,     -0.250239640,     -0.095592834,      0.715512872,
             0.406895459,     -0.4029591

In [47]:
p_conv3d_weight = p_conv3d.weight.detach().permute(0,2,3,4,1).flatten()

In [48]:
p_conv3d_weight

tensor([     0.167345047,     -0.039901048,     -0.163447112,      0.163881779,
             0.089233488,      0.109141409,     -0.153599650,      0.067182690,
            -0.172696546,     -0.106488533,     -0.195103675,     -0.112739369,
             0.046779931,     -0.158758372,      0.118510365,     -0.128597766,
             0.018082216,     -0.094116166,      0.169232070,      0.056312323,
            -0.127299041,     -0.166859791,      0.046977073,      0.105640560,
             0.066785187,      0.071533650,     -0.036201432,      0.197798491,
             0.149581850,      0.044402212,     -0.097265750,      0.041182622,
             0.145801336,      0.085688055,     -0.127393395,      0.097731084,
             0.171908230,      0.116824806,      0.023288608,     -0.157831088,
            -0.009465992,     -0.047914192,      0.078041553,      0.047051430,
             0.000028521,      0.155685842,     -0.065024763,      0.142437607,
             0.059732497,     -0.1361452

In [49]:
p_conv3d_bias = p_conv3d.bias.detach()

In [21]:
p_weight = torch.cat([p_conv3d_weight,p_conv3d_bias],0)

In [22]:
p_weight.numpy().tofile("./padding_3dconv.bin")

In [105]:
torch.onnx.export(p_conv3d, inpu, "padding_conv3d.onnx", input_names=["data"], output_names=["output"], opset_version=9, verbose=True)

graph(%data : Float(2:192, 3:64, 4:16, 4:4, 4:1),
      %weight : Float(6:24, 3:8, 2:4, 2:2, 2:1),
      %bias : Float(6:1)):
  %output : Float(2:162, 6:27, 3:9, 3:3, 3:1) = onnx::Conv[dilations=[1, 1, 1], group=1, kernel_shape=[2, 2, 2], pads=[1, 1, 1, 1, 1, 1], strides=[2, 2, 2]](%data, %weight, %bias) # /opt/anaconda3/envs/d2l/lib/python3.7/site-packages/torch/nn/modules/conv.py:567:0
  return (%output)



### 验证无padding的3D卷积计算

In [67]:
test_m_conv3d = nn.Conv3d(3, 6 , 2 , 2 , 0) #padding_3

In [68]:
test_out = test_m_conv3d(inpu)

In [73]:
test_out.shape

torch.Size([2, 6, 2, 2, 2])

In [72]:
test_out[0,0,0,0,0]

tensor(-0.187062219, grad_fn=<SelectBackward>)

In [74]:
element = inpu[0,:,0:2,0:2,0:2].detach()

In [75]:
weight_0 = test_m_conv3d.weight[0].detach()

In [76]:
element.shape

torch.Size([3, 2, 2, 2])

In [77]:
weight_0.shape

torch.Size([3, 2, 2, 2])

In [79]:
(element * weight_0).sum() + test_m_conv3d.bias[0]

tensor(-0.187062204, grad_fn=<AddBackward0>)