In [83]:
import numpy as np
import tensorflow as tf

root_path = "/Users/bytedance/Downloads/train/"

x_array = np.random.rand(1, 1026)
x_array = x_array.astype(np.float32)
x_array.tofile(root_path + "x_ndarray.bin")
np.save(root_path + "x_ndarray", x_array)

w1_array = 2* np.random.random((256, 1024)) -1
w1_array = w1_array.astype(np.float32)
w1_array.tofile(root_path + "w1_ndarray.bin")
np.save(root_path + "w1_ndarray", w1_array)

w2_array = 2 * np.random.random((1,256)) - 1
w2_array = w2_array.astype(np.float32)
w2_array.tofile(root_path + "w2_ndarray.bin")
np.save(root_path + "w2_ndarray", w2_array)

x = tf.convert_to_tensor(x_array, dtype=tf.float32)
w1 = tf.convert_to_tensor(w1_array, dtype=tf.float32)

b1 = tf.ones((256))
w2 = tf.convert_to_tensor(w2_array, dtype=tf.float32)
b2 = tf.ones((1))

labels = tf.convert_to_tensor([1], dtype=tf.float32)
print("labels: ", labels)

with tf.GradientTape(persistent=True) as t:
    t.watch(x)
    t.watch(w1)
    t.watch(b1)
    t.watch(w2)
    t.watch(b2)
    slice1 = tf.slice(x, [0,0], [-1,1024])
    slice1.numpy().tofile(root_path + "slice1.bin")
    np.save(root_path + "slice1", slice1.numpy())
    
    slice2 = tf.slice(x, [0,1024], [-1, 2])
    slice2.numpy().tofile(root_path + "slice2.bin")
    np.save(root_path + "slice2", slice2.numpy())
    
    fc1_mul = tf.linalg.matmul(slice1, w1, transpose_b=True)
    fc1_mul_numpy = fc1_mul.numpy()
    fc1_mul_numpy.tofile(root_path + "fc1_mul_numpy.bin")
    np.save(root_path + "fc1_mul_numpy", fc1_mul_numpy)
    
    fc1_add = tf.add(fc1_mul, b1)
    fc1_add.numpy().tofile(root_path + "fc1_add.bin")
    np.save(root_path + "fc1_add", fc1_add.numpy())
    
    fc1_relu = tf.nn.relu(fc1_add)
    fc1_relu.numpy().tofile(root_path + "fc1_relu.bin")
    np.save(root_path + "fc1_relu", fc1_relu.numpy())
    
    fc2_mul = tf.linalg.matmul(fc1_relu, w2, transpose_b=True)
    fc2_mul.numpy().tofile(root_path + "fc2_mul.bin")
    np.save(root_path + "fc2_mul", fc2_mul.numpy())
    
    fc2_add = tf.add(fc2_mul, b2)
    fc2_add.numpy().tofile(root_path + "fc2_add.bin")
    np.save(root_path + "fc2_add", fc2_add.numpy())
    
    concat = tf.concat([fc2_add, slice2], 1)
    concat.numpy().tofile(root_path + "concat.bin")
    np.save(root_path + "concat", concat.numpy())
    
    print("concat: ", concat)
    sum1 = tf.reduce_sum(concat, axis=[1], keepdims=False)
    sum1.numpy().tofile(root_path + "sum1.bin")
    np.save(root_path + "sum1", sum1.numpy())
    
    print("sum1: ", sum1)
    loss = tf.nn.sigmoid_cross_entropy_with_logits(labels, sum1)
    loss.numpy().tofile(root_path + "loss.bin")
    np.save(root_path + "loss", loss.numpy())
    
    print("loss: ", loss)
   # bce = tf.keras.losses.BinaryCrossentropy(from_logits=True)
   # bce_value = bce(labels, sum1).numpy()
   # print("bce_value: ", bce_value)

dloss_sum = t.gradient(loss, sum1)
dloss_sum.numpy().tofile(root_path + "dloss_sum.bin")
np.save(root_path + "dloss_sum", dloss_sum.numpy())
print("dloss_sum: ", dloss_sum)

dloss_concat = t.gradient(loss, concat)
dloss_concat.numpy().tofile(root_path + "dloss_concat.bin")
np.save(root_path + "dloss_concat", dloss_concat.numpy())
print("dloss_concat: ", dloss_concat)

dloss_slice2 = t.gradient(loss, slice2)
dloss_slice2.numpy().tofile(root_path + "dloss_slice2.bin")
np.save(root_path + "dloss_slice2", dloss_slice2.numpy())
print("dloss_slice2: ", dloss_slice2)

dloss_fc2add = t.gradient(loss, fc2_add)
dloss_fc2add.numpy().tofile(root_path + "dloss_fc2add.bin")
np.save(root_path + "dloss_fc2add", dloss_fc2add.numpy())
print("dloss_fc2add: ", dloss_fc2add)

dloss_b2 = t.gradient(loss, b2)
dloss_b2.numpy().tofile(root_path + "dloss_b2.bin")
np.save(root_path + "dloss_b2", dloss_b2.numpy())
print("dloss_b2: ", dloss_b2)

dloss_w2 = t.gradient(loss, w2)
dloss_w2.numpy().tofile(root_path + "dloss_w2.bin")
np.save(root_path + "dloss_w2", dloss_w2.numpy())
print("dloss_w2: ", dloss_w2)

dloss_fc2mul = t.gradient(loss, fc2_mul)
dloss_fc2mul.numpy().tofile(root_path + "dloss_fc2mul.bin")
np.save(root_path + "dloss_fc2mul", dloss_fc2mul.numpy())
print("dloss_fc2mul: ", dloss_fc2mul)

dloss_fc1ac = t.gradient(loss, fc1_relu)
dloss_fc1ac.numpy().tofile(root_path + "dloss_fc1ac.bin")
np.save(root_path + "dloss_fc1ac", dloss_fc1ac.numpy())
print("dloss_fc1ac: ", dloss_fc1ac)

dloss_b1 = t.gradient(loss, b1)
dloss_b1.numpy().tofile(root_path + "dloss_b1.bin")
np.save(root_path + "dloss_b1", dloss_b1.numpy())
print("dloss_b1: ", dloss_b1)

dloss_w1 = t.gradient(loss, w1)
dloss_w1.numpy().tofile(root_path + "dloss_w1.bin")
np.save(root_path + "dloss_w1", dloss_w1.numpy())
print("dloss_w1: ", dloss_w1)

dloss_fc1add = t.gradient(loss, fc1_add)
dloss_fc1add.numpy().tofile(root_path + "dloss_fc1add.bin")
np.save(root_path + "dloss_fc1add", dloss_fc1add.numpy())
print("dloss_fc1add: ", dloss_fc1add)

dloss_fc1 = t.gradient(loss, fc1_mul)
dloss_fc1.numpy().tofile(root_path + "dloss_fc1.bin")
np.save(root_path + "dloss_fc1", dloss_fc1.numpy())
print("dloss_fc1: ", dloss_fc1)

dloss_slice1 = t.gradient(loss, slice1)
dloss_slice1.numpy().tofile(root_path + "dloss_slice1.bin")
np.save(root_path + "dloss_slice1", dloss_slice1.numpy())
print("dloss_slice1: ", dloss_slice1)

# Use the tape to compute the derivative of z with respect to the
# intermediate value y.

labels:  tf.Tensor([1.], shape=(1,), dtype=float32)
concat:  tf.Tensor([[-129.7839        0.98735696    0.7084143 ]], shape=(1, 3), dtype=float32)
sum1:  tf.Tensor([-128.08813], shape=(1,), dtype=float32)
loss:  tf.Tensor([128.08813], shape=(1,), dtype=float32)
dloss_sum:  tf.Tensor([-1.], shape=(1,), dtype=float32)
dloss_concat:  tf.Tensor([[-1. -1. -1.]], shape=(1, 3), dtype=float32)
dloss_slice2:  tf.Tensor([[-1. -1.]], shape=(1, 2), dtype=float32)
dloss_fc2add:  tf.Tensor([[-1.]], shape=(1, 1), dtype=float32)
dloss_b2:  tf.Tensor([-1.], shape=(1,), dtype=float32)
dloss_w2:  tf.Tensor(
[[  0.          -7.8467617  -11.526179    -4.42231     -0.47556853
   -9.620237     0.           0.           0.         -13.162345
   -1.8575699   -6.639085    -5.68277      0.          -3.57142
   -1.3193216   -5.371325     0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.         -11.830465   -11.4196       0.
    0.           0.         -30

In [95]:
# label and bias are 1.
input_list = ["x_ndarray", "w1_ndarray", "w2_ndarray"]

fop_name_list = ["slice1", "slice2", "fc1_mul_numpy", "fc1_add",
                "fc1_relu", "fc2_mul", "fc2_add", "concat", "sum1", "loss"]

bop_name_list = ["dloss_sum", "dloss_concat", "dloss_slice2", "dloss_fc2add", "dloss_b2",
                 "dloss_w2", "dloss_fc2mul", "dloss_fc1ac", "dloss_b1", "dloss_w1", 
                 "dloss_fc1add", "dloss_fc1", "dloss_slice1"]
root_path = "/Users/bytedance/Downloads/train/"

In [109]:
#input, weights, bias
iarray_list = {}
for fop in input_list:
    array = np.load(root_path + fop + ".npy")
    iarray_list[fop] = array
    print("name: ", fop)
    print("shape: ", array.shape)
    print("value: ", array)
    print()

name:  x_ndarray
shape:  (1, 1026)
value:  [[0.71418804 0.56033784 0.49481317 ... 0.74936825 0.98735696 0.7084143 ]]

name:  w1_ndarray
shape:  (256, 1024)
value:  [[ 0.9393981   0.9552921  -0.27371365 ... -0.17073244 -0.32269984
   0.57995874]
 [ 0.8257001   0.06280352  0.31610772 ...  0.47219065  0.41119716
  -0.6611977 ]
 [-0.5534487   0.7914612   0.00358489 ... -0.70592123  0.41274068
   0.96728444]
 ...
 [ 0.03463699  0.64945996  0.6045492  ...  0.24949397  0.00740795
   0.6742462 ]
 [ 0.16545077 -0.13656557  0.9199591  ... -0.13381515 -0.83908486
   0.5568845 ]
 [-0.23344351  0.5438589   0.7640936  ...  0.93912816  0.8507972
   0.39825952]]

name:  w2_ndarray
shape:  (1, 256)
value:  [[-0.01191902 -0.17858663  0.27371415 -0.32007444 -0.06232044  0.43536124
  -0.752186   -0.18814331  0.0549641  -0.66654265  0.42793852 -0.08511508
  -0.5518525  -0.94821465  0.7158052  -0.6967367   0.74055225 -0.25280625
   0.53805864  0.8240769   0.7207278  -0.30524793 -0.61667335 -0.35481927
  -0.

In [110]:
#forward part
farray_list = {}
for fop in fop_name_list:
    array = np.load(root_path + fop + ".npy")
    farray_list[fop] = array
    print("name: ", fop)
    print("shape: ", array.shape)
    print("value: ", array)
    print()

name:  slice1
shape:  (1, 1024)
value:  [[0.71418804 0.56033784 0.49481317 ... 0.9713647  0.01746503 0.74936825]]

name:  slice2
shape:  (1, 2)
value:  [[0.98735696 0.7084143 ]]

name:  fc1_mul_numpy
shape:  (1, 256)
value:  [[-1.22722759e+01  6.84676170e+00  1.05261793e+01  3.42230988e+00
  -5.24431467e-01  8.62023735e+00 -1.09130535e+01 -1.42718639e+01
  -1.10874481e+01  1.21623449e+01  8.57569933e-01  5.63908482e+00
   4.68276978e+00 -1.10098696e+01  2.57141995e+00  3.19321632e-01
   4.37132502e+00 -8.88339901e+00 -1.34087744e+01 -7.26461411e+00
  -3.42127876e+01 -1.42136135e+01 -5.56819916e+00 -1.60889721e+01
  -1.06356878e+01 -5.17273045e+00 -2.18661451e+00  1.08304653e+01
   1.04195995e+01 -1.22117090e+01 -5.59189606e+00 -1.54132175e+01
   2.98269310e+01  1.29549503e-01 -1.08945007e+01 -2.54285955e+00
   3.17709756e+00  1.62443590e+00 -1.78813171e+00 -1.24508648e+01
  -4.06645823e+00  1.08542252e+01  7.23612976e+00 -9.58674049e+00
  -2.23424072e+01  8.15151501e+00 -1.38046103e+01

In [105]:
#backward part
barray_list = {}
for fop in bop_name_list:
    array = np.load(root_path + fop + ".npy")
    barray_list[fop] = array
    print("name: ", fop)
    print("shape: ", array.shape)
    print("value: ", array)
    print()

name:  dloss_sum
shape:  (1,)
value:  [-1.]

name:  dloss_concat
shape:  (1, 3)
value:  [[-1. -1. -1.]]

name:  dloss_slice2
shape:  (1, 2)
value:  [[-1. -1.]]

name:  dloss_fc2add
shape:  (1, 1)
value:  [[-1.]]

name:  dloss_b2
shape:  (1,)
value:  [-1.]

name:  dloss_w2
shape:  (1, 256)
value:  [[  0.          -7.8467617  -11.526179    -4.42231     -0.47556853
   -9.620237     0.           0.           0.         -13.162345
   -1.8575699   -6.639085    -5.68277      0.          -3.57142
   -1.3193216   -5.371325     0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.         -11.830465   -11.4196       0.
    0.           0.         -30.826931    -1.1295495    0.
    0.          -4.1770973   -2.624436     0.           0.
    0.         -11.854225    -8.23613      0.           0.
   -9.151515     0.          -4.7164445  -17.795631     0.
    0.         -17.546238     0.          -5.58097    -14.37118
   -3.1980524   -1.9988828   