In [1]:
import numpy as np
from functools import reduce
import torch

In [8]:
def create_data(shape, begin = 0, truncate = False, truncate_base = 13):
    size = reduce(lambda x, y: x * y, shape)
    res = []
    for i in range(size):
        res.append(i % 5)
    return np.array(res,dtype=np.float32).reshape(shape)

In [140]:
data = np.transpose(create_data([1,7,7,1]),(0,3,1,2)) # nchw

In [141]:
# pad data to input unit buffer
pad_data = np.pad(data, ((0,0),(0,0),(0,4),(0,4)), mode='constant') 

In [142]:
pad_data

array([[[[0., 1., 2., 3., 4., 0., 1., 0., 0., 0., 0.],
         [2., 3., 4., 0., 1., 2., 3., 0., 0., 0., 0.],
         [4., 0., 1., 2., 3., 4., 0., 0., 0., 0., 0.],
         [1., 2., 3., 4., 0., 1., 2., 0., 0., 0., 0.],
         [3., 4., 0., 1., 2., 3., 4., 0., 0., 0., 0.],
         [0., 1., 2., 3., 4., 0., 1., 0., 0., 0., 0.],
         [2., 3., 4., 0., 1., 2., 3., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]]], dtype=float32)

In [143]:
kernel3x3_input = pad_data[:,:,0::2,0::2]

In [144]:
kernel3x2_input = pad_data[:,:,0::2,1::2]

In [145]:
kernel3x2_input.shape

(1, 1, 6, 5)

In [146]:
kernel2x3_input = pad_data[:,:,1::2,0::2]

In [147]:
kernel2x2_input = pad_data[:,:,1::2,1::2]

In [148]:
weight = np.transpose(np.array([i % 4 for i in range(1*1*5*5)], dtype=np.float32).reshape((1,5,5,1)),(0,3,1,2))

In [173]:
weight

array([[[[0., 1., 2., 3., 0.],
         [1., 2., 3., 0., 1.],
         [2., 3., 0., 1., 2.],
         [3., 0., 1., 2., 3.],
         [0., 1., 2., 3., 0.]]]], dtype=float32)

In [149]:
weight.shape

(1, 1, 5, 5)

In [150]:
kernel_3x3 = weight[:,:,0::2,0::2] # o,i,h,w

In [151]:
kernel_3x3.shape

(1, 1, 3, 3)

In [152]:
kernel_3x2= weight[:,:,0::2,1::2]

In [172]:
kernel_3x2

array([[[[1., 3.],
         [3., 1.],
         [1., 3.]]]], dtype=float32)

In [153]:
kernel_2x3 = weight[:,:, 1::2, 0::2]

In [154]:
kernel_2x2 = weight[:,:, 1::2, 1::2]

In [155]:
res_p3x2 = torch.nn.functional.conv2d(torch.from_numpy(kernel3x2_input), torch.from_numpy(kernel_3x2), bias=None, stride=1, padding=0, dilation=1, groups=1) 

In [156]:
tmp_array[0,:,:,0]

array([[0, 1, 2, 3, 4, 0, 1, 0, 0, 0, 0],
       [2, 3, 4, 0, 1, 2, 3, 0, 0, 0, 0],
       [4, 0, 1, 2, 3, 4, 0, 0, 0, 0, 0],
       [1, 2, 3, 4, 0, 1, 2, 0, 0, 0, 0],
       [3, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0],
       [0, 1, 2, 3, 4, 0, 1, 0, 0, 0, 0],
       [2, 3, 4, 0, 1, 2, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [157]:
pad_data

array([[[[0., 1., 2., 3., 4., 0., 1., 0., 0., 0., 0.],
         [2., 3., 4., 0., 1., 2., 3., 0., 0., 0., 0.],
         [4., 0., 1., 2., 3., 4., 0., 0., 0., 0., 0.],
         [1., 2., 3., 4., 0., 1., 2., 0., 0., 0., 0.],
         [3., 4., 0., 1., 2., 3., 4., 0., 0., 0., 0.],
         [0., 1., 2., 3., 4., 0., 1., 0., 0., 0., 0.],
         [2., 3., 4., 0., 1., 2., 3., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]]], dtype=float32)

In [158]:
kernel3x2_input

array([[[[1., 3., 0., 0., 0.],
         [0., 2., 4., 0., 0.],
         [4., 1., 3., 0., 0.],
         [3., 0., 2., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)

In [159]:
res_p3x2

tensor([[[[19., 23., 15.,  0.],
          [22., 26., 15.,  0.],
          [16., 12.,  9.,  0.],
          [ 3.,  6.,  2.,  0.]]]])

In [160]:
res_p2x3 = torch.nn.functional.conv2d(torch.from_numpy(kernel2x3_input), torch.from_numpy(kernel_2x3), bias=None, stride=1, padding=0, dilation=1, groups=1) 

In [161]:
res_p2x3

tensor([[[[21., 25., 12.,  9.],
          [24., 18., 19.,  5.],
          [10., 15.,  7.,  1.],
          [ 0.,  0.,  0.,  0.]]]])

In [162]:
res_p3x3 = torch.nn.functional.conv2d(torch.from_numpy(kernel3x3_input), torch.from_numpy(kernel_3x3), bias=None, stride=1, padding=0, dilation=1, groups=1) 

In [163]:
res_p3x3

tensor([[[[18., 14., 16.,  0.],
          [20., 16., 10.,  8.],
          [ 6., 18., 10.,  6.],
          [ 8.,  2.,  6.,  0.]]]])

In [164]:
res_p2x2 = torch.nn.functional.conv2d(torch.from_numpy(kernel2x2_input), torch.from_numpy(kernel_2x2), bias=None, stride=1, padding=0, dilation=1, groups=1) 

In [165]:
res_p2x2

tensor([[[[14.,  2.,  4.,  0.],
          [10.,  8.,  2.,  0.],
          [ 2.,  6.,  0.,  0.],
          [ 0.,  0.,  0.,  0.]]]])

In [166]:
correct  = res_p2x2 + res_p2x3 + res_p3x2 + res_p3x3

In [167]:
correct

tensor([[[[72., 64., 47.,  9.],
          [76., 68., 46., 13.],
          [34., 51., 26.,  7.],
          [11.,  8.,  8.,  0.]]]])

In [168]:
real = torch.nn.functional.conv2d(torch.from_numpy(pad_data), torch.from_numpy(weight), bias=None, stride=2, padding=0, dilation=1, groups=1) 

In [169]:
real.shape

torch.Size([1, 1, 4, 4])

In [170]:
#  to nhwc
real_nhwc = torch.permute(real, (0,2,3,1))

In [171]:
real_nhwc[0,0:2,0:2,0]

tensor([[72., 64.],
        [76., 68.]])

In [59]:
mid = res_p3x2[0,:4,0,0] + res_p2x5[0,:4,0,0]

In [60]:
mid

tensor([240., 232., 240., 248.])

In [61]:
wrong = torch.from_numpy(np.array([318,312,326,328],dtype=np.float32))

In [62]:
wrong 

tensor([318., 312., 326., 328.])

In [63]:
wrong - mid

tensor([78., 80., 86., 80.])

In [64]:
correct - mid

tensor([134., 140., 134., 132.])

In [65]:
res_p3x3[0,:4,0,0]

tensor([134., 140., 134., 132.])

In [66]:
np.transpose(kernel_3x3, (0,2,3,1))

array([[[[0., 1., 2., 3., 0.],
         [1., 2., 3., 0., 1.],
         [2., 3., 0., 1., 2.]],

        [[1., 2., 3., 0., 1.],
         [2., 3., 0., 1., 2.],
         [3., 0., 1., 2., 3.]],

        [[2., 3., 0., 1., 2.],
         [3., 0., 1., 2., 3.],
         [0., 1., 2., 3., 0.]]],


       [[[1., 2., 3., 0., 1.],
         [2., 3., 0., 1., 2.],
         [3., 0., 1., 2., 3.]],

        [[2., 3., 0., 1., 2.],
         [3., 0., 1., 2., 3.],
         [0., 1., 2., 3., 0.]],

        [[3., 0., 1., 2., 3.],
         [0., 1., 2., 3., 0.],
         [1., 2., 3., 0., 1.]]],


       [[[2., 3., 0., 1., 2.],
         [3., 0., 1., 2., 3.],
         [0., 1., 2., 3., 0.]],

        [[3., 0., 1., 2., 3.],
         [0., 1., 2., 3., 0.],
         [1., 2., 3., 0., 1.]],

        [[0., 1., 2., 3., 0.],
         [1., 2., 3., 0., 1.],
         [2., 3., 0., 1., 2.]]],


       [[[3., 0., 1., 2., 3.],
         [0., 1., 2., 3., 0.],
         [1., 2., 3., 0., 1.]],

        [[0., 1., 2., 3., 0.],
         [1.,

### 5x5s1

In [98]:
data_5x5 = np.transpose(create_data([1,6,6,1]),(0,3,1,2)) # nchw

In [115]:
pad_data = np.pad(data_5x5, ((0,0),(0,0),(0,2),(0,2)), mode='constant') 

In [138]:
pad_data

array([[[[0., 1., 2., 3., 4., 0., 0., 0.],
         [1., 2., 3., 4., 0., 1., 0., 0.],
         [2., 3., 4., 0., 1., 2., 0., 0.],
         [3., 4., 0., 1., 2., 3., 0., 0.],
         [4., 0., 1., 2., 3., 4., 0., 0.],
         [0., 1., 2., 3., 4., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]]], dtype=float32)

In [117]:
kernel3x3_input = pad_data[:,:,0:6,0:6]

In [118]:
kernel_3x2_input = pad_data[:,:,0:6,3:]

In [119]:
kernel_3x2_input.shape

(1, 1, 6, 5)

In [120]:
kernel_2x5_input = pad_data[:,:,3:,:]

In [121]:
kernel_2x5_input.shape

(1, 1, 5, 8)

In [122]:
weight = np.transpose(np.array([i % 4 for i in range(1*1*5*5)], dtype=np.float32).reshape((1,5,5,1)),(0,3,1,2))

In [129]:
kernel_3x3_weight = weight[:,:,0:3,0:3]

In [130]:
kernel_3x2_weight = weight[:,:,0:3,3:]

In [131]:
kernel_2x5_weight = weight[:,:,3:,:]

In [132]:
res_p3x3 = torch.nn.functional.conv2d(torch.from_numpy(kernel3x3_input), torch.from_numpy(kernel_3x3_weight), bias=None, stride=1, padding=0, dilation=1, groups=1) 

In [133]:
res_p3x2 = torch.nn.functional.conv2d(torch.from_numpy(kernel_3x2_input), torch.from_numpy(kernel_3x2_weight), bias=None, stride=1, padding=0, dilation=1, groups=1) 

In [139]:
res_p3x2

tensor([[[[11., 18.,  2.,  0.],
          [18., 10.,  6.,  0.],
          [10., 17., 10.,  0.],
          [17., 14.,  9.,  0.]]]])

In [134]:
res_p2x5 = torch.nn.functional.conv2d(torch.from_numpy(kernel_2x5_input), torch.from_numpy(kernel_2x5_weight), bias=None, stride=1, padding=0, dilation=1, groups=1) 

In [135]:
real = torch.nn.functional.conv2d(torch.from_numpy(pad_data), torch.from_numpy(weight), bias=None, stride=1, padding=0, dilation=1, groups=1) 

In [136]:
real

tensor([[[[ 68., 104.,  60.,  31.],
          [104.,  80.,  45.,  32.],
          [ 60.,  45.,  38.,  41.],
          [ 31.,  32.,  41.,  46.]]]])

In [137]:
res_p3x3 + res_p3x2 + res_p2x5

tensor([[[[ 68., 104.,  60.,  31.],
          [104.,  80.,  45.,  32.],
          [ 60.,  45.,  38.,  41.],
          [ 31.,  32.,  41.,  46.]]]])

# TestTranspose

In [28]:
data = [i for i in range(8*8)]

In [29]:
foo = np.array(data).reshape([8,8])

In [30]:
foo

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [31]:
res =np.transpose(foo)

In [32]:
res

array([[ 0,  8, 16, 24, 32, 40, 48, 56],
       [ 1,  9, 17, 25, 33, 41, 49, 57],
       [ 2, 10, 18, 26, 34, 42, 50, 58],
       [ 3, 11, 19, 27, 35, 43, 51, 59],
       [ 4, 12, 20, 28, 36, 44, 52, 60],
       [ 5, 13, 21, 29, 37, 45, 53, 61],
       [ 6, 14, 22, 30, 38, 46, 54, 62],
       [ 7, 15, 23, 31, 39, 47, 55, 63]])

In [33]:
p_4x4 = foo[0:4, 0:4]

In [34]:
np.transpose(p_4x4)

array([[ 0,  8, 16, 24],
       [ 1,  9, 17, 25],
       [ 2, 10, 18, 26],
       [ 3, 11, 19, 27]])

In [35]:
p_4x4_1 = foo[0:4, 4:]

In [36]:
p_4x4_1

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [20, 21, 22, 23],
       [28, 29, 30, 31]])

In [37]:
np.transpose(p_4x4_1)

array([[ 4, 12, 20, 28],
       [ 5, 13, 21, 29],
       [ 6, 14, 22, 30],
       [ 7, 15, 23, 31]])

### 7x7s1

In [71]:
data = create_data([1,32,416,416])

In [ ]:
m = torch.nn.Conv2d(32,4,)

### 测试一个模型是否是合法ONNX

In [2]:
import onnxruntime as ort

In [3]:
sess = ort.InferenceSession("/Users/bob/docs/ByteDance/PNN/converter/modelzoo/deepfillv2_model_places2_360x640_float32.onnx")

InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /Users/bob/docs/ByteDance/PNN/converter/modelzoo/deepfillv2_model_places2_360x640_float32.onnx failed:Protobuf parsing failed.