In [1]:
import numpy as np

In [25]:
a = np.random.uniform(low=0.5, high=13.3, size=(4,4))

In [26]:
b = np.random.uniform(low=0.5, high=13.3, size=(4,4))

In [27]:
c = a @ b

In [28]:
c

array([[119.15990117, 101.27312476, 167.11571851, 209.79393172],
       [ 46.39908619,  30.81082479,  90.82716288, 107.87186194],
       [195.77208206, 130.75332081, 252.91346928, 351.15981709],
       [238.03855444, 172.1090268 , 169.21707574, 278.12896594]])

In [33]:
c0 = np.array([0,0,0,0],dtype=np.float32)
c1 = np.array([0,0,0,0],dtype=np.float32)
c2 = np.array([0,0,0,0],dtype=np.float32)
c3 = np.array([0,0,0,0],dtype=np.float32)
for i in range(4):
    c0 += a[0,i] * b[i,:]
    c1 += a[1,i] * b[i,:]
    c2 += a[2,i] * b[i,:]
    c3 += a[3,i] * b[i,:]



In [34]:
c0.dtype

dtype('float32')

In [32]:
ctest = np.array([0,0,0,0],dtype=np.float32)

In [35]:
c0

array([119.159904, 101.27313 , 167.11572 , 209.79393 ], dtype=float32)

In [36]:
c1

array([ 46.399086,  30.810825,  90.82716 , 107.871864], dtype=float32)