In [2]:
import tensorflow as tf
import tensorflow.nn as nn
import numpy as np

In [5]:
tf.constant([2,1]).shape

TensorShape([2])

In [22]:
@tf.function
def conv_and_pool(x):
    kernel = tf.constant(np.random.rand(3,3,3,12),dtype = tf.float32)
    conv_output = nn.conv2d(x,kernel,1,"SAME") # dilation is None
    window_shape = [conv_output.shape[1] / 2,conv_output.shape[2]/ 2]
    pool_output = nn.pool(conv_output,window_shape,"AVG") #strides and dilations is None
    return pool_output

x = tf.constant(np.random.rand(2,224,224,3),dtype = tf.float32)
conv_and_pool.get_concrete_function(x).graph.as_graph_def()

In [23]:
x = tf.constant(np.random.rand(2,224,224,3),dtype = tf.float32)

In [26]:
conv_and_pool.get_concrete_function(x).graph.as_graph_def()

node {
  name: "x"
  op: "Placeholder"
  attr {
    key: "_user_specified_name"
    value {
      s: "x"
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2
        }
        dim {
          size: 224
        }
        dim {
          size: 224
        }
        dim {
          size: 3
        }
      }
    }
  }
}
node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 3
          }
          dim {
            size: 3
          }
          dim {
            size: 3
          }
          dim {
            size: 12
          }
        }
        tensor_content: "f\342\204>\216\314\314=a\003|?\331\017\231>\031\3251>\034\351\376=\3423\227>[\024\316>\372\022\324>\334\254\331>D\265;>\260uf?\273\303\275

In [1]:
import tensorflow as tf

In [9]:
i_tensor = tf.random.uniform((1,5,5,2048))

In [3]:
fil = tf.random.uniform((16,13,18,112))

In [4]:
bias = tf.random.uniform((112,))

In [11]:
model = tf.nn.avg_pool(
    i_tensor,
    [8,8],
    strides = [2,2],
    padding = "VALID",
    data_format='NHWC',
    name=None
)

In [12]:
model.shape

TensorShape([1, 0, 0, 2048])

In [4]:
# Resize
@tf.function
def resize(x):
    y = tf.image.resize(x,[3,5])
    return y

x = tf.constant(np.random.rand(1,5,5,3),dtype = tf.float32)

In [5]:
tf.io.write_graph(resize.get_concrete_function(x).graph.as_graph_def(),"/Users/bob/Desktop","tf_resize.pb",as_text=False)

'/Users/bob/Desktop/tf_resize.pb'

In [8]:
y = resize(x)

In [7]:
x

<tf.Tensor: shape=(1, 5, 5, 3), dtype=float32, numpy=
array([[[[0.92904377, 0.3808522 , 0.13699697],
         [0.40533274, 0.40954566, 0.28831935],
         [0.33520144, 0.961307  , 0.26638126],
         [0.726246  , 0.01822518, 0.5541069 ],
         [0.539212  , 0.5030131 , 0.38109457]],

        [[0.4344221 , 0.05603006, 0.8752341 ],
         [0.4112504 , 0.20867217, 0.5486552 ],
         [0.21085204, 0.43901724, 0.9860605 ],
         [0.5162153 , 0.6205362 , 0.20131832],
         [0.49768257, 0.18302159, 0.9690177 ]],

        [[0.18978365, 0.49559748, 0.6386571 ],
         [0.18716387, 0.7288908 , 0.8289643 ],
         [0.41162875, 0.9929256 , 0.31303656],
         [0.18135396, 0.05735079, 0.7370532 ],
         [0.72366726, 0.61807024, 0.7385497 ]],

        [[0.14878872, 0.07741605, 0.88859725],
         [0.73981607, 0.48046577, 0.5659911 ],
         [0.4527656 , 0.55138016, 0.4876536 ],
         [0.41873315, 0.4416543 , 0.43606618],
         [0.21382402, 0.00352675, 0.11773629]],

In [9]:
y

<tf.Tensor: shape=(1, 3, 5, 3), dtype=float32, numpy=
array([[[[0.7641699 , 0.27257815, 0.383076  ],
         [0.4073053 , 0.34258783, 0.37509796],
         [0.29375166, 0.7872104 , 0.50627434],
         [0.65623575, 0.21899551, 0.4365107 ],
         [0.52536887, 0.39634925, 0.5770689 ]],

        [[0.18978365, 0.49559748, 0.6386571 ],
         [0.18716387, 0.7288908 , 0.8289643 ],
         [0.41162875, 0.9929256 , 0.31303656],
         [0.18135396, 0.05735079, 0.7370532 ],
         [0.72366726, 0.61807024, 0.7385497 ]],

        [[0.30965877, 0.4518358 , 0.90040296],
         [0.65327257, 0.27978787, 0.71230954],
         [0.1608172 , 0.2771146 , 0.5898945 ],
         [0.7620474 , 0.3004465 , 0.4495032 ],
         [0.29845187, 0.5208679 , 0.20282117]]]], dtype=float32)>